### ISSUE TITLE
Card requires Frigate running with port 5000 exposed

### ISSUE THREAD

**Issue by Heisenberg2980** [dermotduffy/frigate-hass-card#1004]
**Is your feature request related to a problem? Please describe.**
Frigate doesn´t have any authentication mechanism and by default it exposes port 5000 without any authentication mecanism, so anyone inside the network can access all camera feeds, snapshops, recordings, etc. There are options to add an authentication layer, for instance adding a reverse proxy with basic authentication and stop exposing port 5000, but after doing that this card stops working as it get data from port 5000

**Describe the solution you'd like**
I would like to have an option to secure Frigate with authentication and still being able to use this card

**Describe alternatives you've considered**
The only alternative I can see at the moment is leaving the port 5000 exposed

**Comment by dermotduffy** [comment]
The Frigate card does not communicate **directly** to Frigate in any way. All communication is via the Frigate integration in Home Assistant, which proxies requests through to the Frigate backend. As long as you protect your Home Assistant endpoint, using the Frigate card should "just work", since the Frigate integration will proxy your traffic to Frigate backend behind the scenes.

The traffic between HA and the Frigate backend itself is not authenticated in any way, but that is not a problem/issue with the card -- rather Frigate itself, in which case your request is actually for this repo: https://github.com/blakeblackshear/frigate .

**Comment by Heisenberg2980** [comment]
Thank you for the clarification and such a quick response, I will open this issue/question to Frigate repo, happy to close this issue now

**Comment by dermotduffy** [comment]
@Heisenberg2980 You are very welcome. Just keep in mind before you open the issue that what I think you're asking for will already work out of the box without exposing anything extra to the internet, it's just that the _local_ connectivity between HA and your Frigate instance (assuming they are on the same local network) will not be authenticated. That may not necessarily be a priority for the Frigate backend developers to address.

**Comment by Heisenberg2980** [comment]
@dermotduffy yes you are right, it is not an actual issue but more a security concern, as having something with a port exposed in your local network without any type of security, and specially talking about camera feeds, is a bit worrying. Just as an example, any device within your network (including IOT devices) could access Frigate and send all the data to an internet server

**Comment by dermotduffy** [comment]
@Heisenberg2980 Completely understand, just wanted to make sure you knew the magnitude of the security concern -- sounds like you do. Good luck!

**Comment by felipecrs** [comment]
Also, I'd like to mention that, if you install Frigate through the Home Assistant add-on, the port 5000 will not be exposed to your internal network.

**Comment by Heisenberg2980** [comment]
Issue open to Home Assistant Frigate integration: https://github.com/blakeblackshear/frigate-hass-integration/issues/449
