### ISSUE TITLE
Unable to watch a clip back - Error with media stream contents

### ISSUE THREAD

**Issue by badnbusy** [dermotduffy/frigate-hass-card#1011]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

Release with the issue: 4.0.0

Last working release (if known): N/A

Browser and Operating System: Debian 11/Windows 10 with Chrome

The live stream works fine, but when trying to click to playback any clip/recording it just shows: Error with media stream contents. 

I've checked the troubleshooting but it didn't yield anything. The stream plays fine in the Frigate UI (both JPEG and MSE using go2rtc).

What could it be?

Thanks

**Comment by felipecrs** [comment]
Is the clip being recorded with H264 and AAC? Frigate docs mentions that this is a must.

**Comment by badnbusy** [comment]
> Is the clip being recorded with H264 and AAC? Frigate docs mentions this.

The stream is H264 with no audio.

**Comment by felipecrs** [comment]
Have you checked the clip (not the stream) itself? Try to open it in VLC and inspect the codecs.

**Comment by felipecrs** [comment]
I meant downloading the clip and playing locally in VLC

**Comment by felipecrs** [comment]
But anyway if it works in Frigate UI, then probably the codec is correct.

Let's wait for @dermotduffy

**Comment by dermotduffy** [comment]
Suggest: Lets get https://github.com/dermotduffy/frigate-hass-card/issues/1010 working first (same reporter), and then we can debug here if there are still issues.

**Comment by dermotduffy** [comment]
@badnbusy Is this still an issue for you? The new (not yet released codebase) included fixes that made the underlying HLS media player less fragile and more resilient to temporary stream errors. I'm wondering if it has helped?

**Comment by badnbusy** [comment]
> 

Yes, I still can't watch clips back within HA, it spins forever as if it can't play the file...

**Comment by dermotduffy** [comment]
Do they play in the HA media browser (not the card)?

**Comment by dermotduffy** [comment]
@badnbusy Thoughts on the above key question? If the answer is 'Yes' your problem is not with the card but something with your Frigate setup.

You could also try with the latest build `v5.0.0-beta.1` ([link](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v5.0.0-beta.1)) which requires [integration version v4.0.0-rc1](https://github.com/blakeblackshear/frigate-hass-integration/releases/tag/v4.0.0-rc1) and [frigate version v0.12-rc2](https://github.com/blakeblackshear/frigate/releases/tag/v0.12.0-rc2) or later.

**Comment by badnbusy** [comment]
@dermotduffy  Thanks. Upgraded everything to the latest and still the same issue.

However, as you've said, I can't watch the recordings back in the Media > Frigate section in HA either, so I don't know what's going on there? I can stream both the substream and HD stream using go2rtc inside HA so what/how do the recordings differ?

Thanks

**Comment by dermotduffy** [comment]
@badnbusy OK -- so the issue is not with the card. I am guessing it is some class of video codec issue with the recorded media, and your browser cannot play them back (at least in the stream returned for Home Assistant). Suggest opening an issue over in the [Frigate repo](https://github.com/blakeblackshear/frigate/issues), as the issue almost certainly is not with the integration either -- but perhaps the way in which you have Frigate itself configured.

**Comment by badnbusy** [comment]
Thanks @dermotduffy
