### ISSUE TITLE
Add zooming support for media

### ISSUE THREAD

**Issue by jbms** [dermotduffy/frigate-hass-card#1076]
Currently, zooming can be accomplished with the browser's own zoom functionality, which works okay.  However, this does not allow you to just zoom the video while leaving the UI controls around the video such as the timeline, thumbnails, etc. fixed.  It would be great to have support in this card for zooming and digitally panning once zoomed, e.g. using control+mousewheel on desktop browsers and pinch-zoom on mobile/touchscreens.

**Comment by liamstears** [comment]
I just wanted to post to agree to this

Lately frigate and it's plugins/card have come such a long way, the improvements made are extremely impressive and now frigate runs perfectly in my home assistant

What I would like to do though is use homeassistant only and not have to go into the companion app for my cameras and the only reason I have to now is zooming

I use home assistant app on mobile and zooming in cameras really is a must

If this feature could be added it would make it perfect!

Thanks in advance and thanks for all the amazing work so far

**Comment by thornygravy** [comment]
+1 but I totally understand the 5.0.0 upgrade is probably a huge undertaking, thank you for this amazing card

**Comment by dermotduffy** [comment]
The support being added for this issue is really useful in helping me figure out what to work on next -- otherwise it's hard to know, so thank you! As pointed out, getting v5 out the door is the priority, but this is definitely on the todo/to-try list ...

**Comment by liamstears** [comment]
> The support being added for this issue is really useful in helping me figure out what to work on next -- otherwise it's hard to know, so thank you! As pointed out, getting v5 out the door is the priority, but this is definitely on the todo/to-try list ...

We are extremely grateful for the work you have done, v5 was huge and a great upgrade, we are excited to see what comes next :-D

**Comment by dermotduffy** [comment]
I've been thinking and playing around with this and wanted to share an update. I found the following challenges:

1. [**Known**] There's no "magic way" to zoom into a video and get higher quality / resolution output, at least not in a HTMLVideoElement, so best we can do is "artifical" zooming. It's not great, but it's definitely better than nothing.
1. [**Minor**] People naturally use the mouse wheel for zooming. The mouse wheel is _already used_ in the card to cycle through the main media carousel.
1. [**Major**] Android (and possibly iOS -- I don't know) swallow touch events on video players if controls are enabled, i.e. pinching/panning/zooming over an Android video element is extremely annoying since certain (hidden) parts of the video frame will reject touch, and others (where there are no underlying controls) will not -- but yet people use controls all the time, so turning them off is not really an option.

Given 2 & 3 above, I can't think of a way to make this "just work". So instead I propose the following:

* Add a 'zoom mode' button that causes the card to (i) only use the mouse wheel for zooming not moving the carousel, (ii) temporarily disables the media controls. These address 2 & 3 above.
* Zoom mode automatically disables if you change media.
* Mouse cursor is an arrow when in normal mode, or CSS move cursor when in move mode, so there's a visual difference.

I hacked a sample together (not polished code, would need to be re-written entirely) to give you a demo:

![zoom](https://user-images.githubusercontent.com/1136829/232663875-e8160f62-982c-4358-9af0-4414d844eaac.gif)

Other ideas:

* Don't support wheel/panning/pinching and instead have zoom-in/zoom-out/move buttons.

Any thoughts on whether this would be usable, or better ideas?

**Comment by jbms** [comment]
Awesome to hear that you've already looked into this!  Very excited to try it out.

> 1. [**Known**] There's no "magic way" to zoom into a video and get higher quality / resolution output, at least not in a HTMLVideoElement, so best we can do is "artifical" zooming. It's not great, but it's definitely better than nothing.

Yes, that's to be expected ---- we can wait until 6.0 for the "enhance" command.  In principle the player could automatically switch between a lowres and highres video stream, if both are available, depending on the the effective resolution at which it is being displayed on screen, though.

> 2\. [**Minor**] People naturally use the mouse wheel for zooming. The mouse wheel is _already used_ in the card to cycle through the main media carousel.

Potentially you could use control+wheel rather than plain wheel --- that would match what browsers do by default.  You could also use control+drag rather than plain drag to pan around, to avoid interfering with clicking to play/pause.



> 3\. [**Major**] Android (and possibly iOS -- I don't know) swallow touch events on video players if controls are enabled, i.e. pinching/panning/zooming over an Android video element is extremely annoying since certain (hidden) parts of the video frame will reject touch, and others (where there are no underlying controls) will not -- but yet people use controls all the time, so turning them off is not really an option.

I haven't played with this myself, but I think it is likely that there is some workaround available.  For example you may be able to install a capturing event handler on a parent element, create another element on top, etc.  As far as the disabling the controls, I suspect that an overall better user experience would be possible using custom controls rather than the built-in controls, since for example the built-in controls show the progress bar in terms of the particular video clip rather than the overall timeline.  But that is a separate matter.

**Comment by dermotduffy** [comment]
> Potentially you could use control+wheel rather than plain wheel --- that would match what browsers do by default. You could also use control+drag rather than plain drag to pan around, to avoid interfering with clicking to play/pause.

This is likely doable, although there's also benefit in having the experience be somewhat consistent across device types.

> I haven't played with this myself, but I think it is likely that there is some workaround available. For example you may be able to install a capturing event handler on a parent element, create another element on top, etc.

The trouble is getting workarounds to "activate". If we imagine two scenarios: (i) user swiping left to right to adjust the current time in video playback, and (ii) user swiping left to right to pan -- how do we know what the intent is, and thus when the workarounds should be used? Ultimately we end up needing some _other_ input (e.g. a button, a menu, a keypress) -- something to cause the card to treat the same literal UI action differently. 

>  As far as the disabling the controls, I suspect that an overall better user experience would be possible using custom controls rather than the built-in controls, since for example the built-in controls show the progress bar in terms of the particular video clip rather than the overall timeline.

As an aside, I'd like the card to continue to support video playback for non-Frigate devices (today this is just used by `motionEye` cameras, but I'd like to expand it to other camera vendors). Given that constraint, there wouldn't be a world in which we could do away with video controls since the reverse time mapping is only possible using Frigate specific features.

PS: From playing around with it, it actually looks better without the controls! When the controls are on, since the scaling is done at the player level, we end up with a giant pause button, i.e. the player controls scale along with the content. Looks weird.

**Comment by jbms** [comment]
> This is likely doable, although there's also benefit in having the experience be somewhat consistent across device types.

There is necessarily going to be a difference, though, between phone (touch gestures) and desktop (mouse).  While e.g. google maps uses plain mousewheel to zoom, the browser itself uses control+wheel so I think that would be pretty intuitive.

> The trouble is getting workarounds to "activate". If we imagine two scenarios: (i) user swiping left to right to adjust the current time in video playback, and (ii) user swiping left to right to pan -- how do we know what the intent is, and thus when the workarounds should be used? Ultimately we end up needing some _other_ input (e.g. a button, a menu, a keypress) -- something to cause the card to treat the same literal UI action differently.

One common solution is to use two fingers vs one finger --- e.g. two fingers to pan, one finger to switch views.

**Comment by dermotduffy** [comment]
> One common solution is to use two fingers vs one finger --- e.g. two fingers to pan, one finger to switch views.

As the video player swallows the touch input, regardless of the number of fingers, this is tricky. Perhaps we could have a transparent covering div that captures the touch events, then selectively routes them to the "underneath" player if only a single finger is used...

**Comment by dermotduffy** [comment]
Will be in the next build!
