### ISSUE TITLE
Clips don't play: `Error with media stream contents`

### ISSUE THREAD

**Issue by Thorvarium** [dermotduffy/frigate-hass-card#1152]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**  v5.0.0

**Last working release (if known):** n/a

**Browser and Operating System:** Windows 11 Pro version 22H2 build 22621.1555
tried on google chrome 112.0.5615.138 and firefox 113.0

**Description of problem:**
When clicking the clips gallery, the thumbnails display correctly. When I click on one the player displays loading animation forever and the console log displays multiples "Error with media stream contents" in a loop. I tried on android home assistant app and it does work there.
Is also works normally when using the frigate addon to see recordings inside of it. 

![image](https://github.com/dermotduffy/frigate-hass-card/assets/6555325/340fd2d5-4378-43cb-acb0-cc6a8539555f)
**Javascript errors shown in the web inspector (if applicable):**
![image](https://github.com/dermotduffy/frigate-hass-card/assets/6555325/eef8d4ed-0f1b-44ec-9902-5b3009a5b8cb)

**Comment by hanfreakingsolo** [comment]
Just wanted to boost this, having the same issue and viewing recordings is unusable. Latest frigate card, latest frigate integration, and latest frigate docker with updated configs

**Comment by dermotduffy** [comment]
Suggestion to debug: Go to the "Media" tab in Home Assistant and see if you can play the clips from there (entirely separate from the card)? If the answer is no, your issue is not card related but likely some sort of encoding issue / incompatibility.

**Comment by hanfreakingsolo** [comment]
In my case, I can view clips and recording through the media tab but a 30 second clip took over a minute to load. I can watch the same clip with no delay if I view it directly from the frigate ui

**Comment by dermotduffy** [comment]
> EDIT: Clips and recordings are taking forever to load from the frigate ui as well

@hanfreakingsolo Do you see the same error messages as @Thorvarium when you try to play in HA (not the card)? If not, you may have a different issue. In either case, since your clips don't work properly in Frigate itself, your problem is not the card. Recommend [Asking in the Frigate repo](https://github.com/blakeblackshear/frigate).

**Comment by Thorvarium** [comment]
@dermotduffy I cannot play even on the media tab. The media tab works on my android phone, but on windows it have the same infinity loading issue. But, on frigate tab it works :|

**Comment by dermotduffy** [comment]
@Thorvarium Please open an issue on the [Frigate repo](https://github.com/blakeblackshear/frigate). Since playback does not work on the media tab -- your problem is not related to the card (i.e. you have 1 underlying problem, probably a video codec/incompatability, that is causing neither HA nor the card to be able to play your video).

For now I will close this as both cases appear rooted in a Frigate, rather than card, issue. If you report back, when you figure it out, I'd love to add it the troubleshooting FAQ...
