### ISSUE TITLE
Help getting 2-way audio to work

### ISSUE THREAD

**Issue by kksligh** [dermotduffy/frigate-hass-card#1180]
I have Reolink E1 Zoom cameras from what I can tell should work with this set up.  I'm using the RTSP steam and have set up go2rtc in the primary Frigate config file and set up the Frigate card according to the requirements provided.

That said, I can see the microphone icon - when I click it on desktop using Chrome connected to HA via HTTPS, I can see the browser go to a RECORD state but nothing happens from an audio perspective.  The issue comes in where the browser stays in a RECORD state and there's no way to turn it off.  Doesn't matter if I click the record icon or release it, I have to give my browser a hard refresh to get it to stop the RECORD state.  

Maybe my camera doesnt support this, but I'm a novice understanding all the streaming protocols.  I can get audio from the video streams with my current set up and I know the camera has a microphone/speaker.  

I dont have any logs on this, so I'm open to troubleshooting some different scenarios to help.  Thanks in advance!  2-Way Audio is a HUGE deal for HA as its been a big gap in functionality in my opinion.  I'll be glad to help in any way I can.

**Comment by dermotduffy** [comment]
> The issue comes in where the browser stays in a RECORD state and there's no way to turn it off. Doesn't matter if I click the record icon or release it, I have to give my browser a hard refresh to get it to stop the RECORD state.

If I understand this correctly, this is working as intended. The first time you unmute, it will put attach the microphone to the stream (causing the browser to show the record icon, and causing the stream to reset briefly). Thereafter, holding/release the icon will mute/unmute to the connected microphone stream. The browser will automatically disconnect the microphone stream `disconnect_seconds` after the last unmute (default: 60s), and then the browser `record` icon will disappear. See [microphone options](https://github.com/dermotduffy/frigate-hass-card#live-microphone). If you'd rather the microphone stream just connect immediately on card load, use the `always_connected` option.

> I dont have any logs on this, so I'm open to troubleshooting some different scenarios to help. 

Summary: Based on your description, I think the card is doing the right thing but the camera microphone is not working with `go2rtc`.

There are significant requirements to getting 2-way audio to work, called out [here](https://github.com/dermotduffy/frigate-hass-card#using-2-way-audio). You may already meet some of these requirements if the browser is actually getting into record state, but fundamental to 2-way audio working is: 2-way audio must work in go2rtc.

So if it doesn't immediately work for you (as in this case), my advice is to try to get it to work with _just_ `go2rtc` and without the card. If that doesn't work, the card certainly won't. To test that you'd visit the `go2rtc` interface for your Frigate instance. This is usually port `1984` on your Frigate host, but for 2-way audio to work you must take manual steps (i.e. setup a reverse proxy) to access that port over `https`. This may not be comfortable if you're not familiar with networking, but I don't have a better idea right now.

Once at that interface, you'd click on the `2-way-aud` link for the stream in question, the browser will automatically go into 'record' mode and you can test your microphone. Only when that works, can you be sure that the issue is really with the card. It took me multiple attempts with multiple cameras to get one that worked with `go2rtc`, so I'd wager this is the source of your issue and not anything related to the card.

If you have already successfully tested the microphone->speaker output on this camera via go2rtc, and you _still_ can't get it working from the card -- then it sounds like it may be a card issue.

Hope that helps, good luck.

**Comment by kksligh** [comment]
Thanks for the direction - I'll play with this some more

**Comment by dermotduffy** [comment]
Please re-open if you discover an issue with the card! Thanks, and good luck.

**Comment by jojeda654** [comment]
I hope it's ok to piggyback on this. I'm not getting the microphone in the card. How are y'all adding the cameras to Frigate? Was an input_args required? Here's my Frigate config:

```
go2rtc:
  streams:
    front_doorbell:
      - rtsp://[USERNAME]:[PASSWORD]@[CAMERA_IP]/Streaming/Channels/102
      - isapi://[USERNAME]:[PASSWORD]@[CAMERA_IP]:80/
cameras:
  front_doorbell:
    ffmpeg:
      inputs:
        - path: https://[EXTERNAL]/live/webrtc/webrtc.html?src=front_doorbell&media=video+audio+microphone
```

Here's the webrtc API when viewing from Frigate Web UI:

```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://[CAMERA_IP]:554/Streaming/Channels/102/",
      "remote_addr": "[CAMERA_IP]:554",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=1186616, senders=1",
        "0 PCMU/8000, bytes=163200, senders=1"
      ],
      "recv": 1372580
    },
    {
      "url": "isapi://[USERNAME]:[PASSWORD]@[CAMERA_IP]:80/"
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "tcp4 prflx [PC_IP]:61926 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16"
      ],
      "senders": [
        "102 H264, bytes=1186616, receivers=1",
        "0 PCMU/8000, bytes=163200, receivers=1"
      ],
      "send": 1372739
    }
  ]
}
```
When viewed directly from the video+audio+microphone URL, it does work. Here, the ISAPI URL is replaced with `"ISAPI active consumer"`.
```
{
  "producers": [
    {
      "type": "RTSP active producer",
      "url": "rtsp://[CAMERA_IP]:554/Streaming/Channels/102/",
      "remote_addr": "[CAMERA_IP]:554",
      "user_agent": "go2rtc/1.5.0",
      "medias": [
        "video, recvonly, H264",
        "audio, recvonly, PCMU/8000"
      ],
      "receivers": [
        "96 H264, bytes=685349, senders=1",
        "0 PCMU/8000, bytes=95360, senders=1"
      ],
      "recv": 793716
    },
    {
      "type": "ISAPI active consumer",
      "medias": [
        "audio, sendonly, PCMU/8000"
      ],
      "senders": [
        "0 PCMU/8000, bytes=94240, receivers=1"
      ],
      "send": 94240
    }
  ],
  "consumers": [
    {
      "type": "WebRTC/WebSocket async passive consumer",
      "remote_addr": "tcp4 prflx [PC_IP]:61932 related :0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
      "medias": [
        "video, sendonly, VP8, RTX, VP9, H264, AV1, RED, ULPFEC, FLEXFEC-03",
        "audio, recvonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000",
        "audio, sendonly, OPUS/48000/2, RED/48000/2, G722/8000, PCMU/8000, PCMA/8000, CN/8000, TELEPHONE-EVENT/48000, TELEPHONE-EVENT/8000, L16"
      ],
      "receivers": [
        "0 PCMU/8000, bytes=94240, senders=1"
      ],
      "senders": [
        "102 H264, bytes=685349, receivers=1",
        "0 PCMU/8000, bytes=95360, receivers=1"
      ],
      "recv": 106440,
      "send": 794121
    }
  ]
}
```
Any pointers would be appreciated.

**Comment by dermotduffy** [comment]
@jojeda654 [Start here](https://github.com/AlexxIT/go2rtc#two-way-audio). Your go2rtc configuration goes at the top of your Frigate config [as shown here](https://docs.frigate.video/guides/configuring_go2rtc/).

**Comment by jojeda654** [comment]
> @jojeda654 [Start here](https://github.com/AlexxIT/go2rtc#two-way-audio). Your go2rtc configuration goes at the top of your Frigate config [as shown here](https://docs.frigate.video/guides/configuring_go2rtc/).  

I migrated my go2rtc config from the add-on to Frigate, so I know that's correct based on [my camera](https://github.com/AlexxIT/go2rtc#source-isapi). I don't see anything specific for two way audio in the Frigate documentation. 

I shared a truncated config in my first comment, but I can share the full config with my 2 Reolink cameras included if it helps.
