### ISSUE TITLE
2 way audio question

### ISSUE THREAD

**Issue by teymur1988** [dermotduffy/frigate-hass-card#1191]
Hi there

I would like to ask a question about 2 way audio.

Is it possible to get 2 way audio working if go2rtc is installed as an HA addon, and frigate is running on separate machine?

**Comment by dermotduffy** [comment]
> Is it possible to get 2 way audio working if go2rtc is installed as an HA addon, and frigate is running on separate machine?

Only if Frigate itself can be configured to use a different (non-bundled) go2rtc -- I don't think so, but I'm not sure.

 The reason is not related to audio:
   * The card can only talk to the Frigate integration.
   * The integration proxies traffic from the card <-> HA <-> Frigate
   * Frigate itself proxies the traffic to the bundled go2rtc.

Unless there is some way to tell Frigate to use a different go2rtc, I don't think this will work. If there is such a way, I think it'll work just fine as all the proxy paths would continue to work.

**Comment by dermotduffy** [comment]
[Closing as not an issue with the card]
