### ISSUE TITLE
Card not working in companion app on Android 11

### ISSUE THREAD

**Issue by Jasonrobot00** [dermotduffy/frigate-hass-card#1204]
I have a wall mounted android tablet running android 11, on this screen it says that the custom element does not exist, however on my laptop running windows 11, and my iPhone with iOS 16 the card works fine, I have read in the documentation that older browsers may not be compatible, just wanted to confirm this was a compatibility issue.

Other then that card looks great and loving the current features, good work !!

Thank You.

**Comment by dermotduffy** [comment]
Yes. The "custom element does not exist" either suggests the card is not installed correctly, or that the browser in question just cannot understand the Javascript included. Since you have it working on more recent browsers, I'm afraid it is a reasonable assumption that this is a compatibility issue. Sorry. Maintaining compatibility with older browsers incurs quite a bit of maintenance / debugging load, so whilst I try to never make it worse, I also had to make the choice to instead spend the limited time I have to develop on features and support for more recent browsers.

**Comment by dermotduffy** [comment]
[Closing as working, please re-open if you think I missed anything!]

**Comment by zachcheatham** [comment]
The card stopped working on my 9th gen fire tablet wall panel running Android 9 as well.
