### ISSUE TITLE
iOS: Dont show "pause" and dimmed screen when card starts on

### ISSUE THREAD

**Issue by josh-m-sharpe** [dermotduffy/frigate-hass-card#1226]
**Is your feature request related to a problem? Please describe.**
Whenever I view the card on the iOS companion app, moments after the feed starts to work a few things happen:
1) The feed dims and I see the pause icon right in the middle
2) a moment later, "Live: Reolink" pops up in a transaprentish bubble in the bottom right.
3) a few moments later both of these disappear and I see the feed clearly.

**Describe the solution you'd like**
I think `#1` shouldn't happen.  The pause icon is smack in the middle and usually covers the subject/person.

**Describe alternatives you've considered**
I haven't been able to find an option to disable this in all the many options - but maybe I missed it?

**Comment by dermotduffy** [comment]
Hi @josh-m-sharpe , thanks for the issue. I think this is the same as was filed here (see the video, which probably will quickly confirm if this is what you're talking about):

https://github.com/dermotduffy/frigate-hass-card/issues/1069

The conclusion there is that this is an iOS specific behavior. I know of no way to modify/control/stop it. If you know of such a way, let me know -- otherwise I'm not sure what can be done.

**Comment by josh-m-sharpe** [comment]
Seems decently close.   Thanks!
