### ISSUE TITLE
Make it wider

### ISSUE THREAD

**Issue by Sjoerd** [dermotduffy/frigate-hass-card#1232]
Hello,
I can't find anything about making the card on the Hass Dasbhoard wider (like type: card / type: vertical-stack).
Do I miss something or is this not implemented (yet)?

**Comment by dermotduffy** [comment]
The card just expands to fill whatever space is available, so it really depends on what you put the card _into_. For example, to have the card fill the whole dashboard you could use a [panel](https://www.home-assistant.io/dashboards/panel/) dashboard. 

What are you trying to do?

**Comment by Sjoerd** [comment]
I'm trying to make the panel bigger, I would like to give it a two columns width.

**Comment by dermotduffy** [comment]
> I'm trying to make the panel bigger, I would like to give it a two columns width.

But yet not the full width? Maybe something like [layout card](https://github.com/thomasloven/lovelace-layout-card) can help, I'm not sure. But this is a general Home Assistant question rather than anything specific to this card -- your question is really "How can I get any HA card to span 2 columns". Once you answer that, the card will just work within whatever space it is given -- the card cannot control the overall dashboard layout.

**Comment by dermotduffy** [comment]
I don't think there is anything the card can do here, since it simply expands into whatever available space Lovelace gives it and it cannot really control this. Please re-open if you think there's something the card can/should do.
