### ISSUE TITLE
Frigate Hass Card without Frigate NVR

### ISSUE THREAD

**Issue by pergolafabio** [dermotduffy/frigate-hass-card#1243]
**Is your feature request related to a problem? Please describe.**

Hi, ,this just a question... Frigate Hass Card is verry unique!! Its the only card on HA that supports a microphone. A perfect solution for intercom purposes becauuse of the TwoWayAudio with go2rtc. But Frigate nvr is eating CPU resources (no GPU here), because of the ffmpeg proces thats constantly running, when i actually only need to see the stream on an incoming doorbell event

**Describe the solution you'd like**

- Is it possible to use this card WITHOUT Frigate NVR running? I just the webRtc card before with go2rtc , but that card lacks mic functionallity
- Is it maybe possible to send a command to Frigate to stop/start the ffmpeg process?
Maybe an
- Is it possible to use the card to an camera.entity from another integration in combination , but with go2rtc for twowayaudio possibilties +  streaming? With go2rtc as seperate addon?
- ?? another idea maybe?

Thnx for your feedback!

**Comment by dermotduffy** [comment]
> Is it possible to use this card WITHOUT Frigate NVR running? I just the webRtc card before with go2rtc , but that card lacks mic functionallity

Bit of a complicated answer: The card will absolutely work without Frigate. However, you specifically want 2-way audio -- for that you get a hard dependency on go2rtc. In order for HA to access go2rtc, it currently needs to proxy the data via a proxy that the Frigate integration offers. There's an existing feature requests in #1206 to allow the card to take an arbitrary endpoint for go2rtc. With that, you could run go2rtc somewhere else, without Frigate, and have the card talk to it -- but it comes with some limitations on usage (see that issue).

> Is it maybe possible to send a command to Frigate to stop/start the ffmpeg process?

I don't think so, but you should ask on the Frigate backend side (i.e. not here!) as the backend devs may be able to advice you more. If you don't actually want Frigate at all (I think maybe this is what you're saying?), then the combination of {the card + a go2rtc you run yourself + the issue I link above} may work nicely for you, but it would require manual setup on your end.

> Is it possible to use the card to an camera.entity from another integration

Yes.

> ...  in combination , but with go2rtc for twowayaudio possibilties + streaming?

No, since as above the Frigate integration is the only one that is proxying go2rtc traffic.

> With go2rtc as seperate addon?

Also as above, with #1206 this could work for you without Frigate.

**Comment by pergolafabio** [comment]
Great, thnx for answer , I will upvote 1206 :+)

Hopefully this can be happening someday... 
Or the webrtc card with your microphone support :-)

**Comment by dermotduffy** [comment]
> Hopefully this can be happening someday...

It will, it's not a big deal. The upvote will encourage me to prioritize it. Please be sure to read the conditions/restrictions in that issue to avoid disappointment (i.e. will require you to run `go2rtc` behind a `https` proxy if your HA is via `https`, and likely this is not something you'd want to use remotely, since you'd need to expose `go2rtc` itself to the internet).

**Comment by dermotduffy** [comment]
> But i used the webrtc card before, with go2rtc as backend, and no ports were needed for public/remote access?

AFAIK WebRTC card is both an integration and a card, the integration is [proxying](https://github.com/AlexxIT/WebRTC/blob/master/custom_components/webrtc/__init__.py#L189) to the `go2rtc` backend in the same way the Frigate integration is. This proxying avoids the need for port forwarding. When I play with the other issue, I could explore using _that_ proxy as an alternative to the Frigate proxy -- but bottom line is that AFAIK without something proxying, you'd need to worry about ports and security for remote access.
