### ISSUE TITLE
Question: Birdseye card - size, scaling options

### ISSUE THREAD

**Issue by jbishop129** [dermotduffy/frigate-hass-card#1365]
Quick question on `birdseye` view: Is there a way to have the HA card scale to the size of the cameras being displayed, rather than displaying a large black fill area? Screenshot example below. 

My use case is, I have a Fire HD 10 tablet showing an HA Dashboard with specific content, a number of `conditional` cards to make the content dynamic, and so on. Previously I was using individual `frigate` HA cards per-camera, which is a far better view, but the Fire HD tablet is pretty under-powered; over time the 'lag' on the camera feeds would draw back as far as 60 seconds or more. Not ideal. Swapping that out for a single `birdseye` card in `continuous` mode keeps the video feeds near realtime, but, the 'dead space' on the card messes up my layout pretty bad. I presume it is fixed at a 16:9 ratio perhaps?

To that end, if anyone has had success with Fire HD tablets and tuning their `frigate` cards so they dont kill the tablets' already crummy performance, and keep the video streams from falling terribly far behind, I'm all ears!

here's my example. I blurred out my camera feeds ;) The black area I outlined in red is what I'd like to trim out if possible?

![image](https://github.com/dermotduffy/frigate-hass-card/assets/28128937/0993604e-5b2a-450b-8c32-e24b84828773)

**Comment by dermotduffy** [comment]
Hi @jbishop129 ,

The card is not actually assembling the birdseye video, it is simply displaying the stream that the Frigate backend assembles, so this is really a feature request for [Frigate itself](https://github.com/blakeblackshear/frigate/issues) to control what is in that feed.

Related ideas:

* The unreleased code for the card supports a new grid mode, that lets you kind of have a dynamic birdseye mode, where you can control (to some degree) the size of the cameras in the grid. In your case though, since your issue is an underpowered device, this won't actually help you since it's still multiple streams.
* If you combined [scan mode](https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#view-scan-mode-configuration) with the `lazy_unload` option, you could have it so that it loads the (single) camera with the most recent activity, and unloads the others. This is obviously not the same as birdseye, though.

**Comment by dermotduffy** [comment]
Issue sweep: Closing this as it's not really within the cards control. Please re-open if I misunderstand!
