### ISSUE TITLE
Live layout options does not seem effective on dev branch

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#1369]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

dev branch.

**Last working release (if known):**

 Stable release is fine.

**Browser and Operating System:**

Chrome 121

**Description of problem:**

None of the live layout options seems to be doing anything:

https://github.com/dermotduffy/frigate-hass-card/assets/29582865/770dddd3-c7ea-4f49-b168-272329d05b0a

**Frigate card diagnostic information**

```json
{
  "card_version": "5.2.0",
  "browser": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "date": "2024-02-13T16:38:03.386Z",
  "frigate_versions": {
    "624fd5a51dc304193d7e34ab79e1dae3": "5.0.1/0.13.1-34fb1c2"
  },
  "lang": "en",
  "timezone": "America/Sao_Paulo",
  "git": {
    "build_version": "5.2.0-dev+gee2bb25",
    "build_date": "Sun, 04 Feb 2024 14:26:01 GMT",
    "commit_date": "Sat, 3 Feb 2024 16:41:07 -0800"
  },
  "ha_version": "2024.2.1",
  "config": {
    "type": "custom:frigate-card",
    "automations": [
      {
        "conditions": {
          "fullscreen": false
        },
        "actions": [
          {
            "action": "custom:frigate-card-action",
            "frigate_card_action": "live_substream_off"
          }
        ]
      },
      {
        "conditions": {
          "fullscreen": true,
          "media_query": "(min-width: 1500px)"
        },
        "actions": [
          {
            "action": "custom:frigate-card-action",
            "frigate_card_action": "live_substream_on"
          }
        ]
      }
    ],
    "overrides": [
      {
        "conditions": {
          "fullscreen": true
        },
        "overrides": {
          "menu": {
            "style": "overlay",
            "buttons": {
              "substreams": {
                "enabled": true
              }
            }
          },
          "live": {
            "layout": {
              "fit": "contain",
              "position": {
                "x": 50,
                "y": 50
              }
            }
          }
        }
      }
    ],
    "cameras_global": {
      "live_provider": "go2rtc",
      "go2rtc": {
        "modes": [
          "webrtc"
        ]
      },
      "image": {
        "refresh_seconds": 1
      }
    },
    "menu": {
      "buttons": {
        "frigate": {
          "enabled": true
        },
        "snapshots": {
          "enabled": false
        },
        "image": {
          "enabled": false
        },
        "cameras": {
          "alignment": "opposing"
        },
        "timeline": {
          "enabled": false
        },
        "media_player": {
          "enabled": true
        },
        "live": {
          "enabled": true
        },
        "clips": {
          "enabled": true
        },
        "substreams": {
          "enabled": false,
          "priority": 51,
          "icon": "mdi:high-definition",
          "alignment": "opposing"
        },
        "mute": {
          "enabled": true
        },
        "display_mode": {
          "enabled": false
        }
      },
      "style": "outside",
      "position": "top"
    },
    "cameras": [
      {
        "camera_entity": "camera.portao_do_terreiro",
        "webrtc_card": {
          "url": "portao_do_terreiro"
        },
        "go2rtc": {}
      },
      {
        "camera_entity": "camera.video_porteiro_do_terreiro",
        "webrtc_card": {
          "url": "video_porteiro_do_terreiro"
        }
      },
      {
        "camera_entity": "camera.terreiro",
        "webrtc_card": {
          "url": "terreiro"
        },
        "dependencies": {
          "cameras": [
            "terreiro_hd"
          ]
        }
      },
      {
        "camera_entity": "camera.terreiro",
        "title": "Terreiro (HD)",
        "id": "terreiro_hd",
        "webrtc_card": {
          "url": "terreiro_hd"
        },
        "hide": true,
        "go2rtc": {
          "stream": "terreiro_hd"
        }
      }
    ],
    "live": {
      "controls": {
        "next_previous": {
          "style": "none"
        },
        "title": {
          "mode": "none"
        },
        "thumbnails": {
          "mode": "none"
        },
        "builtin": false
      },
      "layout": {
        "fit": "cover",
        "position": {
          "x": 0,
          "y": 0
        }
      },
      "show_image_during_load": true,
      "lazy_unload": [
        "unselected",
        "hidden"
      ]
    },
    "image": {
      "mode": "camera"
    },
    "dimensions": {
      "aspect_ratio": "16:9"
    },
    "performance": {
      "profile": "low"
    },
    "media_viewer": {
      "auto_unmute": [
        "selected",
        "visible"
      ]
    },
    "elements": [
      {
        "type": "custom:frigate-card-conditional",
        "conditions": {
          "view": [
            "live"
          ],
          "camera": [
            "camera.terreiro"
          ],
          "media_loaded": true
        },
        "elements": [
          {
            "type": "custom:frigate-card-menu-submenu-select",
            "entity": "select.camera_do_terreiro_visao_noturna",
            "alignment": "opposing",
            "priority": 52,
            "options": {
              "0": {
                "icon": "mdi:theme-light-dark"
              },
              "1": {
                "icon": "mdi:weather-sunny"
              },
              "2": {
                "icon": "mdi:weather-night"
              }
            }
          }
        ]
      }
    ]
  }
}
```

**Javascript errors shown in the web inspector (if applicable):**

None.

**Additional information:**

**Comment by dermotduffy** [comment]
Thank you very much for testing the `dev` branch! Will investigate.

**Comment by dermotduffy** [comment]
@felipecrs There's definitely work to be done here. As you probably noticed, the card on the dev branch supports a grid of cameras. As such, I'm not sure it makes sense for media layout options to be associated with `live` and `media_viewer`, rather than with the camera itself -- since it is reasonable to want to adjust the dimensions and media layout for 1 camera, but not another.

Proposal:

1. Add `dimensions` and `layout` under the camera config, which would control the dimensions/layout when anything for that camera is displayed (e.g. live or media). This would allow different cameras in the grid to have different dimensions/layouts (e.g. different aspect ratios).
1. Keep `dimensions` at the top level also, since there are views that are not camera specific that still need dimensions (e.g. gallery views, image views, timeline view).
1. Remove support for layout options under both `live` and `media_viewer` (since the layout options for the camera will be used as per 1 above).

I think the only negative effect of the above is in the case where someone wanted _different_ media layouts options, for the same camera, between live and media viewer. But I can't think of a realistic case where this would be wanted...

Opinions? Am I missing anything?

**Comment by felipecrs** [comment]
This is interesting.

I was not expecting to have the live layout configuration to apply to the cameras when they are in grid view mode. In grid view mode, I would expect the cameras to still follow their own aspect ratios and let the grid view arrange them the way it can.

Instead, I was only expecting that when the live view is opened (be it a single camera stream or the multi-camera grid), the live layout settings to be applied.

That said: I understand the need of different live layout settings per camera, but so far, the previous option (global live layout setting) was working very well for me. That's because I have some cameras in 16:9 native for which the layout settings won't make any difference anyway, while for the others it would make a difference.

Finally, even applying the global live layout settings for cameras when in a grid view seems good. Maybe it can even be done by default and no need for a toggle to change this behavior.

So, unless I'm missing some point too, my opinion/suggestion is to keep the global live layout setting, apply it to everywhere: single camera view, grid view card boundaries, camera within the grid view.

**Comment by felipecrs** [comment]
But I would also be ok with your proposal as well. I could still have it set globally through `cameras_global` anyway.

I just think it may be too much work for you. :)

**Comment by dermotduffy** [comment]
> Finally, even applying the global live layout settings for cameras when in a grid view seems good. Maybe it can even be done by default and no need for a toggle to change this behavior.

I don't think this would work as people expect. The live layout options apply on an individual video or image object directly ([it's this CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)). Since the card dimensions are by default "adjust the card to match the contents of the card", the live layout options never have the appearance of having any effect unless also paired with a dimensions setting to constrain the card (like you did in your config). But in grid mode, this dimension constraint cannot be introduced without allowing scrolling -- since the grid library does not appear to support any height constraints.

Scenario: If my global live layout option is letterbox, and I put the card in grid mode, nothing will actually be letter-boxed, since the dynamic grid height cannot actually be constrained like this. Instead, the grid will be unletterboxed and will just scroll within the 16:9 dimensions of the card -- giving the appearance that the layout options were entirely ignored.

From a principle of least surprise, if each camera had its own dimensions, I think this would be a lot clearer.

**Comment by felipecrs** [comment]
Makes sense. 😊
