### ISSUE TITLE
Getting a direct link to a card, instead of being in home assistant persé

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/frigate-hass-card#1381]
**Is your feature request related to a problem? Please describe.**
Imagine getting a notification that someone is at your door. you first have to open home assistant, then go to the correct tab and then perhaps go to full screen, not to mention hit the microphone.

**Describe the solution you'd like**
Being able to get a link to directly go to this card from a browser, in home assistant itself or in a seperate tab.

**Describe alternatives you've considered**
Go2rtc dashboard, but unfortunately this has its limitations with my current use case.

**Comment by dermotduffy** [comment]
The card cannot function outside the context of Home Assistant, but you can navigate directly to a dashboard that you configure (e.g. one with only a single card on it) and pass even commands to the card with this:

https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#query-string-actions

**Comment by borgqueenx** [comment]
thanks for the tip, that already saves some time.
would it be possible to request the microphone to automatically be started, and/or get a microphone momentary button on the screen itself? 
Now, thanks to your tip, i can navigate to the card itself with a browser(can this be made to open up the home assistant app and then the dashboard?) but then i first have to wait until the microphone button appears that takes like 3 seconds, then i have to click the microphone button, which reloads the stream, and also takes like 3 seconds.

**Comment by dermotduffy** [comment]
> would it be possible to request the microphone to automatically be started

Depends what you mean by started. Obviously (!) the card cannot actually unmute your microphone without you requesting it, that would be a huge privacy fail! But it can automatically start a webrtc stream with a microphone stream attached to it, see the `always_connected` parameter (https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#live-microphone).

> And/or get a microphone momentary button on the screen itself?

Do you mean instead of in the menu? (Which already has a momentary button that can just be enabled: https://github.com/dermotduffy/frigate-hass-card?tab=readme-ov-file#using-2-way-audio ).

> Now, thanks to your tip, i can navigate to the card itself with a browser(can this be made to open up the home assistant app and then the dashboard?) 

I'm not sure about this one, if you mean on a mobile device to open the app instead of a browser. I would guess this is possible although have not tried it.

> but then i first have to wait until the microphone button appears that takes like 3 seconds

... this is the webrtc stream loading, there's no way around this one ...

> then i have to click the microphone button

... I don't think there's a way around this either, as there is no way a device/browser will ever allow a URL to unmute the user microphone ...

> which reloads the stream, and also takes like 3 seconds.

... you can get around this one with `always_connected` as described above (it's basically the whole point of that parameter).

Good luck!
