### ISSUE TITLE
Compatibility with Frigate 0.14.0

### ISSUE THREAD

**Issue by pafnow** [dermotduffy/frigate-hass-card#1493]
Hello,
Thanks for the great card, it's a real added value when using Frigate and HA.
Frigate add-on has just been upgraded to version 0.14.0 (https://github.com/blakeblackshear/frigate/releases/tag/v0.14.0) and I was wondering if the card would still be supported if I proceed to the upgrade.
When looking at the changelog, it seems that the changes in this version are quite important.

**Comment by dermotduffy** [comment]
@pafnow I don't know. I still run v13 for now. But I'll add the following:

* This card is actively supported, and so the _intent_ will obviously be that it supports v14.
* No-one has directly told me it doesn't work :-)
* If it doesn't, I can attempt to expedite fix(es) on the current dev branch into a new release, although there might be a bit of a gap in time.

**Comment by mdvickst** [comment]
I use 0.14.0 and can confirm that card works. One thing I'd like to see is alginment with the new events in 0.14.0. 

0.14.0 does a great job of combining events with multiple detections so I get 1 event instead of the multiple that I used to. Example of what it looks like now in 0.14.0 vs the frigate-card. 
<img width="255" alt="image" src="https://github.com/user-attachments/assets/220478d9-9e80-4539-ab1d-ec0b1fb206d5">
VS. 
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/87b0ba8e-0339-46f7-b0b5-12c740ea0276">

Ignore the orientation, but this is the same timeframe.

**Comment by pafnow** [comment]
Thanks for the feedback, i'll proceed to upgrade.

**Comment by stevenmccord** [comment]
Another thing that might be useful in the cards is to mark alerts and detections as reviewed.  Or pull in the groups that you create in the Frigate configuration now.  

Definitely still working for me though, just been using 14 for a little bit and notice myself going to the Frigate UI more with the upgrade.  Thanks!
