### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by HITChris** [dermotduffy/frigate-hass-card#16]
Hi, just a few suggestions I wanted to pass along:

- Card size expands to match snapshot res. (card on the right mirrors the inital size of the card on the left)

![a](https://user-images.githubusercontent.com/34664460/130557655-da7ec4f9-0dfb-49f3-8a19-d4a2da51e1f2.PNG)

- Positioning w/ menu_mode: overlay conflicts with use/positioning of WebRTC card's 'Title' element (below). Perhaps add position-related options including top center, bottom center, and bottom right (just basing those on what would work with WebRTC card's elements + 'ui' option set to true)

![b](https://user-images.githubusercontent.com/34664460/130557866-326f1df9-e7ac-47b3-a509-fcd129df2b6b.PNG)

- Add option to remove 'View Frigate UI' button (reduce button clutter)

- Color/highlight motion sensor icon when entity is binary / '1'

- Add optional buttons to show/toggle camera's 'detect' / 'recordings' / 'snapshots' state. In my case, idea would be to quickly assess whether 'detect' role (in particular) happens to be disabled for some unexpected reason

- Downsize card / button sizes by 25%

Good work!

**Comment by dermotduffy** [comment]
Thanks @HITChris for the really great suggestions. A few clarifications:

*  Card expands to match snapshot resolution: I think what's happening there is you've added an 'object' camera instead of a live Frigate camera (i.e. the issue isn't actually  with the a snapshot viewed in the snapshot gallery). Am I right? (That's not something I had considered as a usecase, but I could see how that would be useful).

* Menu mode overlay: Would the different options should adjust the vertical  position of the menu in your mind? I'm not sure this one is worth it, since the menu can also be moved outside the video frame entirely with  "above" and "below" modes. Any "bottom" based overlay option will interfere with the playing controls. 

* "Color/highlight motion sensor icon when entity is binary / '1'" -- I think you mean when motion is detected, change the icon color, right?

* "Downsize card / button sizes by 25%" -- think you mean the button sizes, not the card size, right? Those buttons are the stock HA button elements in their natural size, shrinking them may not look right ... but I'll experiment!

**Comment by HITChris** [comment]
Feedback:

- **Card expansion** - I'm using a RTSP stream via the WebRTC card ('url' param). The WebRTC card's overall height expands as soon as I click 'View snapshots', + a random Frigate-based snapshot

- **Menu mode** - At least for my use case (above, w/ WebRTC card using a 'Title', and with 'ui' set to True), horizontal alignment would probably be more helpful than vertical. Again just my own UI woes.... but the 'above' and 'below' options expand the WebRTC card's height, which for me (in a dashboard with limited real estate) is a no go

- **Color/highlight** - Right. My use case might be unique... but pulling up a motion sensor's state history isn't (at least via this button) something I'd do with any real frequency. Just speaking for myself -- when it comes to tacking functionality into a camera/surveillance-focused card, I'd take more advantage of things that give a quick indication of general statuses (hence motion sensor status via highlighting, optional buttons showing highlighted status of camera's Frigate roles, etc.)

- **Downsize card** - I don't think that takes away from the user experience though, so no worries on this one. Only reason I brought it up was because, relative to all other (video player related) UI elements in AlexxIT's WebRTC card, frigate-hass-card's buttons seem a good bit larger

Thanks!

**Comment by dermotduffy** [comment]
Sincere thanks for the really great feedback @HITChris . I've opened separate issues for all the items you suggest so I (or someone else) can work through them 1-by-1. Follow along on the individual bugs, thanks again.
