### ISSUE TITLE
Delay/wait in automations

### ISSUE THREAD

**Issue by Jack77777777** [dermotduffy/frigate-hass-card#1777]
**[REQUIRED] Describe the feature you'd like:**

I use fully kiosk browser on my wall mounted tablets. When someone is ringing an HA automation reloads start url, because my frigate card is on that page. I would like have frigate card go to fullscreen after the time fully kiosk needs to load the HA start url and close fullscreen after xx seconds. I could close fullscreen manually if only delayed fullscreen is possible.

**Comment by dermotduffy** [comment]
`sleep` action: https://card.camera/#/configuration/actions/custom/README?id=sleep

Example usage: https://card.camera/#/examples?id=change-to-live-temporarily

Note that Javascript (like the card) cannot enable fullscreen unless the user has interacted with the card. This makes sense because otherwise, just think what random websites could do. You might use the [expand](https://card.camera/#/configuration/actions/custom/README?id=expand) action as a replacement which doesn't have this limitation.

**Comment by dermotduffy** [comment]
Let me know if this is not sufficient.

**Comment by Jack77777777** [comment]
Very busy actually. Hopefully i can test it at the weekend.
