### ISSUE TITLE
Allow a way to fallback to frigate live view when webrtc is not available

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#232]
**Is your feature request related to a problem? Please describe.**
WebRTC does not work well for me when I'm outside of my home.

**Describe the solution you'd like**
It would be super if the card could provide a way to fallback to Frigate's live view if WebRTC fails to load.

**Describe alternatives you've considered**
Creating two cards perhaps. Not beautiful.

**Additional context**
None

**Comment by felipecrs** [comment]
Recently, the WebRTC works 1/5 of the times for me... I even switched to JSMPEG by default. I don't know if there would be a way to detect whether WebRTC has started the stream with success but if there is, I wish I could configure the card to use JSMPEG (which loads fast and works 100% of the times) while WebRTC is not yet available.

**Comment by dermotduffy** [comment]
There was a recent release of the WebRTC card ([releases](https://github.com/AlexxIT/WebRTC/releases), a release 10 days ago, first one since June). Could that be the trigger in the change you're seeing? Although there have been many Frigate card releases, so could equally be something here.

I didn't respond on this feature request, but that's mostly because I'm still thinking about it (and working on the existing backlog).  Initial thoughts are:
 * I'm not sure the card _should_ support this. Not just because of the extra technical complexity, but because it kind of feels like the issue is that WebRTC isn't working and we should fix _that_ -- versus trying to hack in rarely used fallback options that would need detection logic, and configuration and documentation. In short: I think this is probably a niche usecase?
 * The hard part might be telling what the state of WebRTC is, i.e. how to detect when to failover.

Currently I'm in the middle of implementing multiple camera support. One idea I had that combines these, is to allow the user to have 'Front door JSMPEG' and 'Front door WebRTC' as different cameras in the same card. The user would be the one that chooses the card to display, so not seamless like you're suggesting, but maybe better than nothing? How would this suit your usecase?

PS: Thanks for explaining why you'd still like WebRTC, as my initial reaction was "Why not just stick with JSMPEG then?".

**Comment by felipecrs** [comment]
> There was a recent release of the WebRTC card (releases, a release 10 days ago, first one since June). Could that be the trigger in the change you're seeing? Although there have been many Frigate card releases, so could equally be something here.

Well, honestly, I have been applying updates to my HA so frequently that I think I don't want to waste time troubleshooting it... especially considering that the new WebRTC version that was released is a requirement for running with HA 2021.12.

> I'm not sure the card should support this. Not just because of the extra technical complexity, but because it kind of feels like the issue is that WebRTC isn't working and we should fix that -- versus trying to hack in rarely used fallback options that would need detection logic, and configuration and documentation. In short: I think this is probably a niche usecase?

You know what, I totally agree. I will be closing this issue because of it. Feel free to reopen, though.

> One idea I had that combines these, is to allow the user to have 'Front door JSMPEG' and 'Front door WebRTC' as different cameras in the same card. The user would be the one that chooses the card to display, so not seamless like you're suggesting, but maybe better than nothing?

Definitely, this would be very reasonable. I would then, switch to WebRTC if I want to PTZ control the camera, for example.

> PS: Thanks for explaining why you'd still like WebRTC, as my initial reaction was "Why not just stick with JSMPEG then?".

About that specifically, I have no particular preference over WebRTC. In fact, I wish in the future I/we won't need it at all:

1. JSMPEG latency can be improved, very likely: https://github.com/blakeblackshear/frigate/issues/2139#issuecomment-995419070

2. Looking at [JSMPEG](https://github.com/phoboslab/jsmpeg) documentation, it seems that it supports decoding audio as well. I saw that the card uses `audio: false`, but turning it to `true` does not help. Perhaps the source stream from Frigate isn't supplying any audio.

**Comment by felipecrs** [comment]
WebRTC complexifies a lot my whole setup as well:

- Install WebRTC integration (and keeping it up to date)
- Configuring the Frigate card to use it, with my preferred options like `mse: false`
- Setting up https://github.com/snowzach/rts2p as a repeater for my camera's feed
- Expose RTS2P 5554 port over internet so I can view WebRTC's feed outside of my network

All that considering that it does not work at all on iOS (which I don't use). And that, as mentioned, it barely works normally as well, lol.
