### ISSUE TITLE
Stop/Pause clip before moving to other one

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#268]
**Is your feature request related to a problem? Please describe.**
When I watching a clip in event viewer and let's say I move to next clip while video is still running, I can still hear an audio from previous clip and can't hear the audio from new clip. When you move further, it keeps playing all the videos in background until it ends.

**Describe the solution you'd like**
Stop/Pause current video when moving to previous or next clip in event viewer.

EDIT: noticed similar problem with multiple camera setup. When you switch from one live feed to other one audio seems to be combined from both streams.

**Comment by dermotduffy** [comment]
This is obvious in retrospect (my cameras don't have audio, so never noticed before).

I think this will be ~straightforward for Clips. For live cameras I think it'll be more involved, as it will need to work across the different live providers -- and when revisiting a live camera we would want it to 'fast-forward' to real live rather than just play from where it was last paused.

PS: Thank you for all the testing with the unreleased code, and the bug reports, sincerely appreciate your help in making this card better.
