### ISSUE TITLE
Previous camera stream keeps fetching data

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#283]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** `main` branch

**Last working release (if known):**

**Browser and Operating System:** Firefox 96.0, Ubuntu 20.04

**Description of problem:**

When I watch one camera live stream and then switch to other one, I noticed it keeps fetching stream data from previous camera. I know there were new changes(https://github.com/dermotduffy/frigate-hass-card/issues/268) for pausing live streams when switching between so I don't know if it's a bug or desired behaviour. Did you had in mind to pause stream when you switch to next one and when you come back it resumes from position you left? Maybe then it's better to add some option to override this behaviour so it will drop connection as soon you switch to next camera(to save network resources).

**Javascript errors shown in the web inspector (if applicable):**

```
```

**Additional information:**

I'm using two identical cameras in one card, one for WebRTC and other one for default stream with audio(WebRTC does not support AAC).

**Comment by dermotduffy** [comment]
HTML5 video elements don't have a 'stop' control, so I think the options are either:

1. Pause [as implemented today, depending on underlying implementation may cause streaming to continue sounds like].
2. "Fake stop" [Pause, but then reset video time to 0 -- this may be a dead end if the stream continues as with option #1.
3. Drop the connection entirely, causing a full video reload & delay when you scroll back to this camera.

I need to experiment with #2 a little, but otherwise I think your suggest boils down to "Add an choice between pause and disconnect when a user stops looking at a live stream".

Let me know if I'm misinterpreting.

**Comment by peledzius** [comment]
You understood correctly. For my case the best option would be 3rd one.
