### ISSUE TITLE
Use frigate-hass-card with UI Minimalist theme?

### ISSUE THREAD

**Issue by mcdent** [dermotduffy/frigate-hass-card#287]
I'd like to be able to use this frigate card with the above theme, see
`https://ui-lovelace-minimalist.github.io/UI/
`
Wondering if this is possible? Or can somebody suggest the code I can test with please?
My test dashboard below.

![IMG_20D720F54251-1](https://user-images.githubusercontent.com/8769856/151165357-4adbafe2-0010-411e-ac6a-a71664495ceb.jpeg)

**Comment by NickM-27** [comment]
Do you have frigate setup in HASS? Should be able to just get this card from the store and set it up, or are you having issues trying to do that?

**Comment by mcdent** [comment]
> Do you have frigate setup in HASS? Should be able to just get this card from the store and set it up, or are you having issues trying to do that?

Ahh, excellent thanks, I was able to add the card to another dashboard and use the code editor to copy the required code snippet for my dashboard, thanks for pointer!
![IMG_1502](https://user-images.githubusercontent.com/8769856/151179989-68e47900-5bdb-47b0-b203-f3f7bcb92a76.PNG)

**Comment by NickM-27** [comment]
Do you know if these cards are provided by the UI-minimalist-lovelace or are these custom cards that specifically support it?
If it's the former then there isn't anything the card can do itself to know this theme is being used, the theme will need to make its own adjustments or you can use something like `card-mod` to make the changes yourself.

**Comment by mcdent** [comment]
I believe this is a custom card made for Frigate, which probably knows nothing of the UI-minimalist-lovelace, so I shall have a look at card-mod and see if I can figure it out. Cheers

**Comment by NickM-27** [comment]
Right, I meant the other cards in the screenshot. Anyhow, sounds like card-mod is the best bet.

**Comment by mcdent** [comment]
Oh sorry, yes they are part of UI-minimalist-lovelace

**Comment by dermotduffy** [comment]
Not familar with UI-minimalist-lovelace -- that looks really slick! From a quick look around, all those cards seem custom for UI-minimalist-lovelace rather than something an existing card can implement? I don't see any other camera/picture type cards -- maybe it's not in keeping with the [style requirements](https://ui-lovelace-minimalist.github.io/UI/development/card_style_guide/)? 

So yeah, doesn't seem like something that can be supported natively here. If you find a way to get card-mod to implement that style, be sure to post it back here and we can put it in the docs. Note that you may struggle with card-mod, see #284 .

**Comment by dermotduffy** [comment]
Going to close this, as I don't think there's anything that can be done on this end. Please re-open if anyone finds something to the contrary.
