### ISSUE TITLE
Camera selection action should be configurable

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#294]
* Same view different camera.
* Or: default view different camera.

**Comment by peledzius** [comment]
What if your default view is image and you want to open live view after selecting camera in menu, but also want to keep existing behaviour for live, clips, snapshots?

**Comment by dermotduffy** [comment]
@peledzius Out of the box, that just wouldn't be supported as proposed. You could add your own submenus ([docs](https://github.com/dermotduffy/frigate-hass-card#special-elements)) that are conditional on the view so that when you're in the image view the items in the submenu do something different. That also has hidden challenges though, so let me step back ...

Can you describe your setup a bit -- why is image your default, and how do you typically want to use the card? [Maybe there's another way to get what you want]

**Comment by peledzius** [comment]
I'm using default view for image because I like to see what's happening on the camera without loading the live view and wasting network resources. It doesn't make sense for me to open live view by default when I've an opportunity to take a glance to one image.  Whenever I need to look live feed, I'm pressing appropriate button for that. 

I've setup multi camera configuration with same camera, one for HLS stream and other for WebRTC. WebRTC is 2nd in list so when I'm in image view and select WebRTC in camera menu it would make sense to open live view without pressing Live view button.

Now my first comment make some uncertainties. Because it's same camera for both providers, it doesn't matter to keep current camera selection action for clips or snapshots. Maybe make it configurable like: 

- Specific view for different camera

Is that making sense?

**Comment by dermotduffy** [comment]
> Is that making sense?

Yes, thank you for the description. So I think the new option should be:

**Camera Submenu View**
* [_Default_] "Same view"
* [Or] Choose any view from the normal view list (e.g. snapshots, snapshot, live, image, clips, clip)

I think that would address your use case?

**Comment by peledzius** [comment]
> I think that would address your use case?

Yeah.
