### ISSUE TITLE
Investigate adding the new native HA WebRTC support

### ISSUE THREAD

**Issue by dermotduffy** [dermotduffy/frigate-hass-card#326]

**Comment by felipecrs** [comment]
This would be nice when Frigate adds the ability to act as a RTSP proxy rather than just RTMP. I suspect that without it, for people to leverage WebRTC they would still need to create custom camera entities adding their camera's RTSP data to it. Seems to be in the plans for Frigate 0.10.

Of course the above would be nicer in order to reduce direct connections with the camera, but it would also be nice if the card could talk to Frigate API (if it had an API for that, of course) to retrieve the original RTMP feed as configured in the `frigate.yaml`. That would also prevent users from having to create custom camera entities for all the cameras they want to use with WebRTC. But I suspect the API does not support it, for good reasons, and if the above becomes true, there would not be a need anyway.

**Comment by dermotduffy** [comment]
As per my update on #331 , direct card <-> Frigate communication is not desirable. Yes, once Frigate supports exposing RTSP I think it'll open some new doors for us. For now though, adding this would let people have a better experience with Nest cameras (the only integration I could find that currently uses the new native support, although I presume it'll grow).
