### ISSUE TITLE
Question: does the card talks with Frigate API directly?

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#331]
This is not an issue, neither a feature request. In fact, if Discussions were enabled, I would open a Question there instead. Sorry for opening it anyway, and I would very appreciate any reply.

The question is: does the card talk with the Frigate API from within the HA ingress? I'm asking this, because I we are struggling a lot to make a similar communication to happen in https://github.com/TECH7Fox/Asterisk-add-on/pull/57.

If yes, don't bother explaining, I can of course check the source code to understand how it's done. I could not find any other example of such thing happening: frontend talking with an http server exposed by an addon over the HA ingress. Neither good documentation about it.

**Comment by dermotduffy** [comment]
Hi @felipecrs ,

No the card does not talk to the Frigate API directly -- this is by design. Cards can only (read: should only) talk to Home Assistant. For HA users that use Home Assistant Cloud, or otherwise expose HA to the internet (but presumably not Frigate) -- if the card tried to talk to the Frigate backend directly, it would break.

The card exclusively talks to HA / the Frigate integration. Anything the card needs from the Frigate server, needs to come via the Frigate integration (see [views.py](https://github.com/blakeblackshear/frigate-hass-integration/blob/master/custom_components/frigate/views.py) which does the proxying from the backend).

So for users using the Frigate add-on, the communication flow is roughly like this:

```
Frigate add-on <-> (ingress) <-> Frigate integration / Home Assistant <-> (views.py which proxies http and websockets) <-> Frigate card
```

**Comment by felipecrs** [comment]
Wow, this is extremely helpful. Proxying the required endpoint through the integration is the solution then.

Thank you, a lot!

**Comment by felipecrs** [comment]
> Frigate add-on <-> (ingress) <-> Frigate integration / Home Assistant <-> (views.py which proxies http and websockets) <-> Frigate card

@dermotduffy are you sure the Frigate Integration talks to the Frigate addon over the Hassio Ingress and not directly through http://ccab4aaf-frigate:5000 instead?

**Comment by felipecrs** [comment]
Checking more deeply, I think the integration indeed does not talk to Frigate over the HA ingress, but directly.

[DEFAULT_HOST = "http://ccab4aaf-frigate:5000"](https://github.com/blakeblackshear/frigate-hass-integration/blob/609fe8738910cfdc956ef33e49d246e92448933d/custom_components/frigate/const.py#L44)

**Comment by felipecrs** [comment]
I suppose the Ingress is only meant for human interface, I guess.

**Comment by blakeblackshear** [comment]
You specifically asked if the lovelace card talks directly to frigate. It does not. The integration talks directly to frigate and integrates information directly into home assistant native components and provides some proprietary endpoints that the card uses.

**Comment by felipecrs** [comment]
That was all I needed to know. Thanks a lot, both of you.

**Comment by felipecrs** [comment]
Refs https://github.com/TECH7Fox/Asterisk-add-on/blob/main/asterisk/CHANGELOG.md#130, the goal there is to make Home Assistant a viable client for doorbells using SIP protocol, without having to rely on third-party apps.
