### ISSUE TITLE
Improve menu layout versatility

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#376]
For example, these are my cameras:

![image](https://user-images.githubusercontent.com/29582865/153918840-2a114daf-6da0-4fbe-9d71-6953133a1a2d.png)

The issues with the available layouts are:

1. Hidden/Overlay/Hover Top -> clashes with my camera's watermark
2. Hidden/Overlay/Hover Bottom -> clashes with UI buttons when using HA or WebRTC live view provider
3. Hidden/Overlay/Hover Left -> As it starts from top to bottom, also clashes with the watermark
4. Hidden/Overlay/Hover Right -> Too close to my PTZ controls

Of course, my current best option is to use "Above" or "Below", but if I had a "Overlay Top Right", that would be my preference.

So, the suggestion is to have some additional config modes, so that:

```diff
  'none',
- 'hidden-top',
+ 'hidden-top-left',
+ 'hidden-top-right',
- 'hidden-left',
+ 'hidden-left-top',
+ 'hidden-left-bottom',
- 'hidden-bottom',
+ 'hidden-bottom-left',
+ 'hidden-bottom-right',
- 'hidden-right',
+ 'hidden-right-top',
+ 'hidden-right-bottom',
- 'overlay-top',
+ 'overlay-top-left',
+ 'overlay-top-right',
- 'overlay-left',
+ 'overlay-left-top',
+ 'overlay-left-bottom',
- 'overlay-bottom',
+ 'overlay-bottom-left',
+ 'overlay-bottom-right',
- 'overlay-right',
+ 'overlay-right-top',
+ 'overlay-right-bottom',
- 'hover-top',
+ 'hover-top-left',
+ 'hover-top-right',
- 'hover-left',
+ 'hover-left-top',
+ 'hover-left-bottom',
- 'hover-bottom',
+ 'hover-bottom-left',
+ 'hover-bottom-right',
- 'hover-right',
+ 'hover-right-top',
+ 'hover-right-bottom',
- 'above',
+ 'above-left',
+ 'above-right',
- 'below',
+ 'below-left',
+ 'below-right',
```

But I think it could be greatly simplified to end user if new attributes were added. Like:

```js
style: "hidden", "overlay", "hover", "flat" // "flat" is equivalent to "above" and "below"
position: "top", "bottom", "left", "right" // for "flat" style, the options "top" and "bottom" controls the previous "above"/"below".
corner: "top", "bottom", "left", "right" // configuration UI should only show "top" and "bottom" when position is "left" or "right", and vice-versa
```

**Comment by dermotduffy** [comment]
Thanks for the feature request @felipecrs !

Does `corner` mean the corner that the buttons 'flow' from? i.e. consider these two:

* hover-top-left
* hover-top-right

Is the difference that the second one is effectively right-to-left aligned?

> style: "hidden", "overlay", "hover", "flat" // "flat" is equivalent to "above" and "below"

This makes sense. Not sure about 'flat', maybe 'outside'? 

> position: "top", "bottom", "left", "right" // for "flat" style, the options "top" and "bottom" controls the previous "above"/"below".

This makes sense. "left" and "right" for outside/flat would not be valid options.

> corner: "top", "bottom", "left", "right" // configuration UI should only show "top" and "bottom" when position is "left" or "right", and vice-versa

(Tangent: I'd really like to avoid the UI editor needing to know about the semantic relationship between options otherwise we have to effectively put menu code in the editor to know what combinations are valid together)

As above, if I understand this, this is effectively the menu alignment. So I think there are actually only two valid options:

* Top-to-Bottom / Left-to-Right (`menu.align: ltr-ttb`)
* Bottom-to-Top / Right-to-Left (`menu.align: rtl-btt`)

...because that naming is so terrible, maybe we accept all of top/bottom/left/right. 

So in all I think my tweaked proposal is:

```
menu.style: [hidden, overlay, hover, outside]
menu.position: [top, bottom, left, right] // When style is outside, only top/bottom will be valid.
menu.align: [top, bottom, left, right] // Only top/bottom have any effect for left/right positioned menus, only left/right have any effect for top/bottom positioned menus.
```

Thoughts?

**Comment by felipecrs** [comment]
I agree with all you said! :-D

**Comment by dermotduffy** [comment]
Great! FYI: I've marked this for v4, so it might be a while. Have to finally push v3 out the door...

**Comment by Hukuma1** [comment]
Was just about to ask about ability to add PTZ buttons to have an all-in-one video card solution. Will be following this. Thanks so much!

**Comment by felipecrs** [comment]
@Hukuma1 but PTZ is already possible, check the README for examples. Here is mine:

![Screenshot_20220222-133416_Home Assistant.png](https://user-images.githubusercontent.com/29582865/155176587-7b8cee7a-482d-4f99-a033-78052b159fb4.png)

**Comment by Hukuma1** [comment]
My Google-Fu has failed me. Thank you! Works amazing right-out-of-the-box. Especially since my cameras are amcrest :D

**Comment by dermotduffy** [comment]
Will be in the v4 release.
