### ISSUE TITLE
Submenu occasionally renders in the wrong place

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#447]
**Checklist:**

- [x] I updated to the latest version available (actually I built the latest from source)
- [x] I cleared the cache of my browser

**Release with the issue:**
master

**Last working release (if known):**
Not sure if this behavior happened on v3.0.0-rc.1 or not.

**Browser and Operating System:**

Android Companion app latest beta version.

**Description of problem:**

https://user-images.githubusercontent.com/29582865/156897346-21b1aacb-d72c-4299-86e5-622c8e79409d.mp4

**Additional information:**

I didn't know what to put in the title...

**Comment by dermotduffy** [comment]
There's a long story here: I've spent a ludicrous amount of time trying to get that menu to render in the right place in all conditions, and I haven't yet found a way. There is a negative interaction of some kind between HA layout itself and the menu component, such that when the menu is in fixed positioning (so that the menu can extend beyond the boundaries of the card) it renders the menu in the wrong place.

I can get it to work correctly when the menu uses *relative* positioning, but that has other negative effects as then I need to allow card contents to render outside the boundary of the menu (and so curved corners don't work as expected).

Right now, my choice is:
   * Use relative menu positioning [downside: curved corners do not work correct in `above` / `below` menu mode]
   * Use fixed positioning: Does not work correctly in all cases. Seems fine on the browser, but Android app gets it wrong sometimes as per your demo.

Put bluntly, I'm not going to spend more time on this. If you have a strong preference on the above choices, or perhaps more patience to figure this out yourself, let me know!

**Comment by felipecrs** [comment]
Got it. So, this is why I have rounded corners now (I didn't have it in v3.0.0-rc.1).

> Put bluntly, I'm not going to spend more time on this. If you have a strong preference on the above choices, or perhaps more patience to figure this out yourself, let me know!

That's absolutely reasonable. I'm a poor UI developer, but I'll see what I can do. Thank you for the detailed response.

**Comment by dermotduffy** [comment]
> Got it. So, this is why I have rounded corners now (I didn't have it in v3.0.0-rc.1).

Exactly so. The alternative isn't so bad (we can make the card body have corners -- just not the `above` / `below` menu), so depending on how annoying you/we/others find the menu, we can always resort to that. At least it's predictable...

> That's absolutely reasonable. I'm a poor UI developer, but I'll see what I can do. Thank you for the detailed response.

OK, good luck! Here is the current scheme, happy to chat on discord if you'd like to learn more about what I learned on the issue, etc.

https://github.com/dermotduffy/frigate-hass-card/blob/main/src/components/submenu.ts#L105

**Comment by tbrausch** [comment]
I would vote for relative positioning.  I have the same problem with the menu being displayed well below the camera window - but it also does this in the chrome browser on windows (see attachment).  Not having rounded corners on the menu is a small price to pay (assuming it does not affect the main camera window
![Untitled](https://user-images.githubusercontent.com/45288916/157429448-ffc02f0f-687a-4c5b-93fb-19ff4539b375.jpg)
.

**Comment by dermotduffy** [comment]
Think you might be right @tbrausch, especially since you have this outside of the Android context: losing the curves on the menu is probably a price worth paying. @felipecrs, what do you think?

**Comment by felipecrs** [comment]
I agree! Rounded curves are nice, but they are a smaller detail than this.

**Comment by dermotduffy** [comment]
OK, deal -- I'll go back to relative, and remove the rounded corners.

**Comment by felipecrs** [comment]
@dermotduffy if I understood well, you fixed it without having to get rid of the rounded curves. Right?

**Comment by dermotduffy** [comment]
@felipecrs ~Yes. It works, although it's not as clean an implementation were it not for the menu `fixed` issue, so I'm not that happy about it. It does have the advantage of a kind of nice double curve: if you look closely at the below you'll see a curve over the buttons, and also a curve on the video pane.

![Screenshot from 2022-03-13 13-47-00](https://user-images.githubusercontent.com/1136829/158078642-06dec967-1c68-4a2b-a1af-16d19c90fbd4.png)

**Comment by felipecrs** [comment]
Got it. Thank you!
