### ISSUE TITLE
No video from Amcrest AD410

### ISSUE THREAD

**Issue by CZonin** [dermotduffy/frigate-hass-card#470]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
3.0

**Last working release (if known):**
2.1.0

**Browser and Operating System:**
Windows 11/Chrome and Android/Home Assistant App

**Description of problem:**
Live video from Amcrest AD410 continuously loads, regardless of live provider. My other Amcrest cameras are working without any issues in 3.0.

**Javascript errors shown in the web inspector (if applicable):**

```
Not sure how to find this, will provide if someone can help me.
```

**Additional information:**
Loving 3.0 aside from this issue, been waiting for it for awhile!

**Comment by dermotduffy** [comment]
Hi @CZonin ,

That's weird.

* Does that particular Amcrest camera work fine in Home Assistant otherwise? i.e. if you make a picture glance card (not a frigate card), or open the camera entity (press 'e' on your HA dashboard) -- does the video load?
* Do the video feeds show up for this camera on the Frigate UI? (For both the 'Live' and 'Debug' choices on the UI?)

Both the card and HA share an almost-identical component for playback, so I'm trying to figure out if this is a card issue, or a more general HA issue you are having with this 1 particular camera.

**Comment by CZonin** [comment]
Looks like it was an error on my end, sorry! I never reserved the IP for the camera and it changed.
