### ISSUE TITLE
Expand `lazy_unload` to support either/both lazy unloading on carousel moves or tab being hidden

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#471]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 3.0.0

**Last working release (if known):**

**Browser and Operating System:** Firefox, Chromium

**Description of problem:**

With `lazy_load: true` and `lazy_unload: true` when you watch HA live provider camera stream and then switch to other tab, video player is paused but it keeps fetching stream data in the background. When you switch back tab, video is unpaused and it resumes from the position you left it. Based on documentation, it should unload camera and not pause when `lazy_unload: true`.

Actually, this is the behaviour I would like, but with one correction - do not pause the video and keep it running in the background, but keep existing `lazy_unload` behaviour when switching through cameras in carousel. 

Why keep running camera stream in the background? It's because I have cameras with audio support and I would like to continue listen camera stream while browsing in other tabs, unless it's paused/stopped by me.

**Comment by dermotduffy** [comment]
Having a hard time understanding, but I _think_ this is what you're saying:

1. There is mismatch between what the documentation says (that changing tabs should unload a live camera) and what you actually see (changing tabs does NOT unload a live camera).

2. SEPARATELY, you'd actually rather that video streams didn't pause at all when you change tabs (so you can listen to the audio in the background).

Is that right? If yes:

* 1 is a bug. I think lazily_unloading when you change tabs is probably correct behavior. If you're turning on lazy_unload, you care about bandwidth usage, and so unloading when you change tabs makes sense.

* 2 might be a feature request, e.g. `auto_pause`. When you move in the carousel, the camera should _always_ be paused. But when you change tabs, if `auto_pause` is false the stream is left running, otherwise it's paused.

Am I following you correctly? Do you have a different view or suggestion?

**Comment by peledzius** [comment]
> Is that right?

Yes, you understood me well.

**Comment by dermotduffy** [comment]
OK, well then how about this:

* Maybe `lazy_unload` should not be a boolean, but instead should be `["both", "carousel", "hidden", "none"]`, where `carousel` unloads when you move away in the carousel, `inactive` when you change tabs, `both` in either case, or `none` for never.

* We'd also need a new feature `auto_pause`. It could have the same 4 values: ["both", "carousel", "inactive", "none"].

**Comment by dermotduffy** [comment]
Heh, yeah, just updated my comment to say the same thing!

**Comment by dermotduffy** [comment]
[Split into two separate bugs]

**Comment by dermotduffy** [comment]
@peledzius Opinion sought: 

**Test-case**: I have this setting set to 'hidden' (so scrolling the carousel does not lazily unload, but changing tab does). I scroll through the whole carousel and lazily load cameras {1,2,3}, then with {2} selected, I change tab. Should {2} be lazily unloaded only, or all of {1,2,3}?

I think the answer is {1,2,3}, i.e. _all_ cameras. Otherwise we're only unloading the camera that happens to be visible, and leaving the unselected cameras elsewhere in the carousel still loaded. Seems weird?

**Comment by dermotduffy** [comment]
Will be in v4.0.0.

**Comment by peledzius** [comment]
@dermotduffy sorry for late reply. I will test everything you implemented as soon as I can. I really appreciate your work!
