### ISSUE TITLE
Add support for a card-wide `dark` mode

### ISSUE THREAD

**Issue by peledzius** [dermotduffy/frigate-hass-card#496]
**Is your feature request related to a problem? Please describe.**
Frigate card stock image is beautiful, but at night/dark it irritates my eyes because of bright colours. It also doesn't fit well with dark theme.

**Describe the solution you'd like**
Allow user to override stock image, or even better: transform current stock image to dark theme friendly and add an option to choose between light and dark image.

I'm not an image editor expert, but I used GIMP to lower brightness on image and this is the example which I would use for override:

![image](https://user-images.githubusercontent.com/24360494/160266285-f7ee45e7-e448-4219-b5ff-d2367771085c.png)

**Comment by NickM-27** [comment]
What does your config look like? The image can be set to a custom url or a camera entity so it's unclear to me why you're not seeing that option?

**Comment by peledzius** [comment]
> What does your config look like? The image can be set to a custom url or a camera entity so it's unclear to me why you're not seeing that option?

Sorry, I didn't make it clear.

This is related to https://github.com/dermotduffy/frigate-hass-card/issues/398 where stock image is shown to avoid failed login attempts or when image is not available, but the image itself cannot be changed.

**Comment by dermotduffy** [comment]
I think there can be only one stock image. It's really intended as a "last resort" / failback type image -- the image is encoded into the Frigate card JS itself to make sure there's no external web fetches so "nothing can go wrong" when it needs to be displayed. Adding more stock images would increase the size of the JS with limited value.

Some options I imagine:

1. Automatically detect when HA `darkMode` is enabled, and automatically apply a CSS brightness filter to a display image (no matter what that is). Please note this only works (AFAIK) when using the default HA theme, as it lets you choose auto/dark/light in the profile settings. If the user overrides with a specific theme selection, it will always appear to the card that `darkMode` is off.

2. Manually allow the user to specify a darkMode (`auto`, `dark`, `light`). Auto would follow the behavior from option 1, dark light would force a particular choice.

3. [Totally different] Instead of using the stock image as a fallback, use the URL provided (if any). This could be useful if someone is using `image` view with the camera entity (like I think you are @peledzius), in that you could _also_ specify a URL and when the camera entity is not available the URL would be used instead.

Please note that all three options would only apply to the `image` view, i.e. if you change to `live` or `clips` the above has no effect.

Thoughts?

**Comment by peledzius** [comment]
1. Won't help me, because I'm using custom theme, which is actually the same as HA default dark theme (to set dark mode across every device by default)
2. Sound nice, doesn't require any network resources.
3. Gives you more control of the image view, but maybe is more complicated one to implement?

I would prefer any, just which is easier for you to implement. :)

**Comment by dermotduffy** [comment]
OK, I think 2 is the best path forwards and straightforward to implement.

**Comment by dermotduffy** [comment]
@peledzius ... thinking about this more, why should this only apply to the `image` view, and not all the other views? Should this be a card-wide option that just applies the brightness filter at the top level?

New suggestion:

4. As with option 2, except filter applies to the whole card not just `image` view. The new variable would be `view.dark_mode` and allowable values would be:

* 'on': Dark-mode is **en**abled card-wide always.
* 'off': Dark-mode is **dis**abled card-wide always.
* 'auto': Dark-mode is enabled either when the user has `dark` mode chosen in their profile (i.e. not using a custom theme but has selected 'dark') **OR** when the `timeout_seconds` interaction handler expires, i.e. would be dark until it is interacted with in this mode.

**Comment by peledzius** [comment]
Great suggestion! If I understand correctly, brigthness filter will only apply to stock image or something else too?

**Comment by dermotduffy** [comment]
In option 4 it would apply to literally everything in the card (e.g. clips / live view / gallery / image view stock or non-stock -- everything).

**Comment by peledzius** [comment]
Tried out dark mode. Guess I misunderstood how this dark_mode would apply for everything in the card. Now every item in the card it's kinda too dark for me. I would prefer everything like it was before and only make dark_mode apply to stock image. Maybe it's possible to make a dark mode override for stock image/screensaver? Sorry if I wasn't specific before.

**Comment by dermotduffy** [comment]
> I would prefer everything like it was before and only make dark_mode apply to stock image.

I still don't understand why dark mode would ever be a feature of the `image` view specifically though, i.e. I believe you happen to use `image` as the default, but `image` isn't even enabled by default so I imagine most people use something else.

Maybe it's just too dark and I such tweak it up? Or am I missing something that is unique to image mode?

**Comment by peledzius** [comment]
Actually, I don't want to make image view dark at all. I would only prefer dark mode for stock image(bird flying in blue sky), which is embedded in the card.

**Comment by dermotduffy** [comment]
Ah, so just making the stock image _always_ darker is really what you're after?

When the current dark mode is in `auto`, isn't that almost the same. i.e. the stock image would appear darker, but the moment you interact with the card it goes back to normal.

**Comment by peledzius** [comment]
> Ah, so just making the stock image always darker is really what you're after?

Yes!

> When the current dark mode is in auto, isn't that almost the same. i.e. the stock image would appear darker, but the moment you interact with the card it goes back to normal.

I don't think it's the same, I've set `timeout_seconds: 0` and it's always dark, even after interaction with card. And what I'm after: making darker stock image, which is displayed briefly before image url/camera snapshot loads, or image url/camera snapshot is unavailable. Of course with `mode: screensaver` stock image could be darker too.

**Comment by dermotduffy** [comment]
> I don't think it's the same, I've set timeout_seconds: 0 and it's always dark,

You're right, with `timeout_seconds` set to 0, there is no interaction timer so we'd have to choose it always dark or always not dark.

> And what I'm after: making darker stock image, which is displayed briefly before image url/camera snapshot loads,

I think the crucial bit here is you want the stock image darker, but NOT the image url/camera snapshot darker once it loads, right? This is the bit I had missed before.

I think this is a _very_ niche case you're after here, where even when there _is_ user interaction you want a dark stock image (but otherwise the rest of the card is not dark!). So I think just allowing the stock image to be overridden with by the URL is the best idea. Then you can set it to whatever you want, including just a darker version of the stock image. Make sense?

**Comment by dermotduffy** [comment]
@peledzius Implemented in #683, but I'll hang on to make sure this will work for you!

**Comment by peledzius** [comment]
This does the job for me. Tested, looks like it does not override stock image if camera snapshot is unavailable(camera is off) - I still see original stock image.

**Comment by dermotduffy** [comment]
@peledzius Would you mind trying again. PR is the same, but now with:

* Re-clicking the image button should re-fetch the image.
* [New] If the camera entity is unavailable it'll fallback to the URL image.

**Please note**: If there's an image load error, the stock image will be displayed. This is by design, so we can be stateless and avoid getting stuck in a loop (bad image -> set to url -> bad image -> set to url, etc). Unavailable entities are not an image load error.

**Comment by peledzius** [comment]
Cool, everything seems OK! Thanks.
