### ISSUE TITLE
Card not getting loaded in Lovelace

### ISSUE THREAD

**Issue by erenoglu** [dermotduffy/frigate-hass-card#583]
**Checklist:**
[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Release with the issue:**
v3.0.0
**Last working release (if known):**
N/A
**Browser and Operating System:**
Arch Linux, Google Chrome v101

**Description of problem:**
My HA is installed in a Docker container.  I also have HACS installed in the container.
I then installed the frigate-hass-card using HACS. Then I added the below in the configuration.yaml and restarted my container. 
```
lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module

```
But the card is not getting loaded. 

The message in Docker start console is:
`homeassistant  | 2022-05-12 15:24:37 WARNING (MainThread) [homeassistant.components.lovelace] Lovelace is running in storage mode. Define resources via user interface`
The message I get in HACS front page is:
```
Not loaded in Lovelace
You have 1 Lovelace elements that are not loaded properly in Lovelace.
```
If I add "mode: yaml" in the configuration, then it loads, but then I lose the capability to make updates to the dashboard using UI, so I can't add the card (and I dont want to add it using yaml coding). 

Is this by design or is there a bug here? It's the first time I'm trying to install this card, so I may be doing a mistake or misunderstanding how it works.

**Comment by dermotduffy** [comment]
Try this. In your dashboard:

* Three dots menu on the top right
* Edit Dashboard
* Manage resources
* Add resource
   *  URL: /hacsfiles/frigate-hass-card/frigate-hass-card.js
   * Type: Javascript module
* Hit create

No editing your configuration.yaml at all. Then try adding a Frigate card.

Does that work?

**Comment by dermotduffy** [comment]
[If yes, I think this is actually a request to improve the documentation for those with frontend resources outside of YAML]

**Comment by erenoglu** [comment]
OK, I deleted the card from my previous setup, I removed the repository, restarted HACS. 
I restarted HA and then added back the repository. Now when I tried to check the "Manage Resources", I saw this already there:
```
URL:  /hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=394082552300
Type: Javascript Module
```
And then I tried to add the Card and it worked! So I think this is good. 

Though the video type selection looked weird with 5 options, top one selected, but no text (does not show what is that option). This may be another bug though...

```
Live view provider for this camera
(o)  --> This one is already selected but no description visible
( ) Automatic
( ) Home Assistant (i.e. HLS, LL-HLS, WebRTC native)
( ) Frigate JSMpeg
( ) WebRTC Card (i.e. AlexxIT's WebRTC Card)
```

**Comment by dermotduffy** [comment]
> And then I tried to add the Card and it worked! So I think this is good.

Great! I updated the installation instructions, as they were really aimed at YAML users rather than (modern out of the box) Home Assistant users, and I think that may have made them more confusing for you in this case.

> Though the video type selection looked weird with 5 options, top one selected, but no text (does not show what is that option). This may be another bug though...

I don't think that's a bug, at least if it looks like this:

<img width="356" alt="Screen Shot 2022-05-13 at 9 26 24 PM" src="https://user-images.githubusercontent.com/1136829/168410630-cd82b93d-f927-4b17-9fa1-954104911e2a.png">

You just don't have that parameter set in your config, so nothing is selected. Please re-open if I'm missing the point!

**Comment by sshaikh** [comment]
Just some feedback - Brand new frigate (and card) non-yaml user, but I also had to manually add the resource as per https://github.com/dermotduffy/frigate-hass-card/issues/583#issuecomment-1125624554, and I didn't see any instructions for that either. I _do_ see the instructions for yaml users though. Should this resource have been made available automatically on installation or have I missed the instruction?

**Comment by bob454522** [comment]
> Just some feedback - Brand new frigate (and card) non-yaml user, but I also had to manually add the resource as per [#583 (comment)](https://github.com/dermotduffy/frigate-hass-card/issues/583#issuecomment-1125624554), and I didn't see any instructions for that either. I _do_ see the instructions explicitly for yaml users though (which I don't think I am?). Should this resource have been made available automatically on installation or have I missed the instruction?

same here- was Confused on this and spent a decent amount of time trying to find this new frigate-hass-card.  Since I was on a brand new HA install I expected the card to be available after I had downloaded /installed the frigate-hass-card though HACS.    

It's still not clear if there is any scenario in which a user can simply click download via HACS and then have access to the card (ie wo having to do add module ->
```
url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
type: module
```

to be clear - i am brand new to Home assistant (but not IT/tech) , so prehaps this is more an issue on my end.  
thanks!
