### ISSUE TITLE
Auto-rotate to landscape when entering full-screen in mobile apps

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#590]
**Is your feature request related to a problem? Please describe.**

When I am in my mobile device, I frequently like to put a camera in full-screen (because the screen is already too small).

But when I do so, the screen keeps in portrait mode (as it was there before), and I have to manually change the screen orientation (I don't keep screen orientation as auto in my device).

But it gets a little worse:

- After entering full-screen (portrait), if I change my screen orientation to landscape, instead of just putting the camera in landscape mode, the view is reset to Lovelace, so I have to click in full screen button again.

**Describe the solution you'd like**

Just like the YouTube app, when I click in the full-screen button, the orientation auto-rotates to landscape.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by felipecrs** [comment]
I think it is worth mentioning that full screen in portrait mode does not make the card bigger, so I don't think there is a use case for keeping it.

https://user-images.githubusercontent.com/29582865/168443528-c53fcb50-a1f8-45f2-a0cb-8c4e16eb64e2.mp4

**Comment by dermotduffy** [comment]
As discussed on discord -- sadly whilst this is a great idea I do not believe this is currently possible, since Lovelace appears to resets the whole dashboard when the orientation changes, which causes the card to disconnect from the DOM, which means it loses fullscreen and the orientation change cannot "stick".

Closing as infeasible as a result -- but let me know if you (or anyone else) has a better idea of how to try to make this work.

**Comment by felipecrs** [comment]
Thank you very much for the investigation you drove.

**Comment by felipecrs** [comment]
- Refs https://github.com/home-assistant/frontend/issues/13726
