### ISSUE TITLE
Card should expand in sidebar and panel mode

### ISSUE THREAD

**Issue by scooper1** [dermotduffy/frigate-hass-card#61]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
v1
**Last working release (if known):**

**Browser and Operating System:**
chrome  windows 10

**Description of problem:**
card size not working well with sidebar layout option used to be full width 

![image](https://user-images.githubusercontent.com/14822945/132261967-8050b211-53b5-4117-8fe6-e51cd72e03bd.png)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Hi @scooper1 . I think you're saying on the prior version of the card, it stretched all the way across with a 'sidebar' Home Assistant dashboard -- but now it is as per-screenshot -- is that right?

**Comment by scooper1** [comment]
Yelp

**Comment by dermotduffy** [comment]
Thanks @scooper1 . I think I made some changes there because Safari wasn't honoring the aspect ratio. Just to confirm what you want to happen here ideally:

 - The card would expand to full width of the sidebar (across all modes: live, media gallery, media playing).
 - Since clips are 16/9 aspect ratio most likely, to maintain that aspect ratio when you play a clip or view live, you'd expect to see the height of the card increase significantly (as if the height isn't allowed to increase, then we'll unavoidably get what's in your bug screenshot).

I am understanding this right? [I have never really used 'sidebar' mode before in HA, so not sure how you expect it to behave]

**Comment by scooper1** [comment]
just want full width   and expect the height of the card to match the width aspect ratio
thanks

**Comment by unrly** [comment]
Is this the same issue? Seeing this in both Chrome on Windows 10 and in Fully Kiosk on a Nexus 7 in a dashboard in Panel Mode, only card in there:
![image](https://user-images.githubusercontent.com/24898502/132372603-a1820d49-61c0-4b07-9919-0575eec3055b.png)

**Comment by dermotduffy** [comment]
@unrly Yes, I *believe* this is the same issue. The height is being forced to a max cap in the released version (due to some issues with Safari). I'm working on forcing the aspect ratio, rather than the height.  I'll make sure to test against both Sidebar & Panel mode.

**Comment by unrly** [comment]
Thanks @dermotduffy - issue fixed in panel mode.
