### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by Delta1977** [dermotduffy/frigate-hass-card#760]
Google Chrome - Develop Console complains about 
Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
for function : 
`function cy() {
    var t = [];
    var e = {
        add: function(i, n, o, s) {
            return void 0 === s && (s = !1),
            i.addEventListener(n, o, s),
            t.push((function() {
                return i.removeEventListener(n, o, s)
            }
            )),
            e
        },
        removeAll: function() {
            return t = t.filter((function(t) {
                return t()
            }
            )),
            e
        }
    };
    `

**Comment by dermotduffy** [comment]
Hi @Delta1977 , thank you for the issue report and helping make the card better. I am aware of this Chrome complaint, that warning is caused by a fundamental mechanism within the Carousel library ([Embla](https://github.com/davidjerleke/embla-carousel/)) that this card uses.

Please see [this description](https://github.com/davidjerleke/embla-carousel/issues/62#issuecomment-628569509) of why the carousel cannot implement passive listeners.

Fundamentally, the issue here is one that the warning is technically correct, but not actually useful. Embla is a small and performant library that does its job well and cannot easily use non-passive listeners. The only alternative I can think of is changing the Carousel entirely, which is a considerable amount of work for no gain beyond getting rid of this warning message.

My suggestion is for me to update the documentation to specifically mention this warning.

Let me know if you have thoughts or better ideas, and thanks again for reporting.

**Comment by Delta1977** [comment]
👍

**Comment by dermotduffy** [comment]
[Going to keep this open as a reminder to myself to update the docs!]
