### ISSUE TITLE
Scan mode weirdness with 4 Cameras

### ISSUE THREAD

**Issue by scho0ck** [dermotduffy/frigate-hass-card#809]
**Checklist:**

- [ ✓] I updated to the latest version available
- [✓ ] I cleared the cache of my browser

**Release with the issue:**
v4.0.0-rc.2

**Last working release (if known):**
-
**Browser and Operating System:**
Chrome Firefox Windows as well as Linux

**Description of problem:**

Using the new scan mode with 4 cameras setup sometimes it works just fine sometimes it does not switch to the active cam or sometimes it randomly switches to the first camera. How can we debug this?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
Hi @scho0ck , thanks for the bug report. Will definitely need more information:

* Please hold down the Frigate menu button and paste the diagnostics that show up.
* Can you explain in words what the weirdness is? When you say it does not switch, do you mean the flashing border shows up but the camera doesn't move, or do you mean the card just doesn't change at all? If the latter, are you sure Frigate is detecting the occupancy/motion? First step there is -- whichever trigger entity you have configured scan mode with -- see if the state of that entity is correct or incorrect in your eyes. If it's correct -- the issue is with the card. If it's incorrect -- the issue is with the integration or the Frigate backend.
* Would it be possible to take a screen capture of the 'weirdness' happening?

**Comment by scho0ck** [comment]
Hi, currently not home I’ll post some details along with the debug details next week

**Comment by dermotduffy** [comment]
Hi @scho0ck Any more information you can provide here? Thanks in advance.

**Comment by dermotduffy** [comment]
Please re-open the bug with details to facilitate debugging, thanks!
