### ISSUE TITLE
Style Issue - Corner rounding

### ISSUE THREAD

**Issue by conorlap** [dermotduffy/frigate-hass-card#816]
**Checklist:**

- [Y] I updated to the latest version available
- [Y] I cleared the cache of my browser

**Release with the issue:**
[v4.0.0-rc.3](https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.3)
**Last working release (if known):**
N/A - this issue has been there for a while 
**Browser and Operating System:**
Firefox & Edge on macOS and the Android Companion app

**Description of problem:**

I'm getting these weird style issues again, all the corners of the card are displaying this on multiple browsers - the rounding isn't correct.

<img width="204" alt="Screenshot 2022-09-05 at 10 20 01" src="https://user-images.githubusercontent.com/57415184/188415476-3476a3e8-4fe6-4d48-9500-001ef543c894.png">

The standard WebRTC custom card displays fine with nice rounded corners:

<img width="149" alt="Screenshot 2022-09-05 at 10 20 10" src="https://user-images.githubusercontent.com/57415184/188415497-50a6dd98-959e-432e-8091-a0cfbf6b06ac.png">

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

HA theme that I use: https://github.com/Kibibit/hass-kibibit-theme

**Comment by dermotduffy** [comment]
OK -- I think this is fixed now, and tested with that (nice) theme you linked to. This is a pretty exasperating problem since it should be ridiculously easy to implement these corners, but because of a bug in a (totally unrelated) HA frontend component, I have to jump through all sorts of hoops to get both it ... and this corner rounding ... both working, so I fear this may not be the last time this bites.

**Comment by conorlap** [comment]
Brilliant, working fine here now - thanks @dermotduffy !! 🥳

**Comment by conorlap** [comment]
Hey @dermotduffy 
This issue's back with v6.0.0-beta.4
