### ISSUE TITLE
'Live' popup repeats continuously

### ISSUE THREAD

**Issue by cwelsh1812** [dermotduffy/frigate-hass-card#839]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** v4.0

**Last working release (if known):**v3.0

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

https://user-images.githubusercontent.com/42767976/192262726-7af90132-bbce-4b0b-b8f3-cc2c58c98092.mov

**Comment by dermotduffy** [comment]
Interesting! Can you hold down the Frigate menu button and paste the diagnostics? Are you using card_mod or anything else that may impact the normal rendering?

**Comment by dermotduffy** [comment]
PS: You can turn off the title popups temporarily from the card edit window, as that's pretty annoying.

**Comment by dermotduffy** [comment]
> I don't seem to be able to find the setting to turn off the title popup ?

![no-titles](https://user-images.githubusercontent.com/1136829/192305047-cb2b87a2-784d-4111-a93b-06f52041428f.png)

PS: You are specifying `webrtc-card` as your live provider, but have not specified any webrtc card configuration, which is not a valid combination (either choose a different live provider, or include the details required for the webrtc-card provider). Not suggesting this is the trigger for the bug, but it could be:-)

![webrtc](https://user-images.githubusercontent.com/1136829/192305557-348041f4-3863-43d0-a37c-5b1a669f525f.png)

**Comment by cwelsh1812** [comment]
Thanks.  I have specified the web-rtc card config now and it has made no change.

**Comment by Sarah-Connelli** [comment]
I have the same issue now and again. Is it at all possible to just disable those message-toasts altogether? I never liked them in my use-case and often get in the way when you want to watch a recording and fullscreen it straight away, ie have to wait till the floating message goes away before being able to click fullscreen/volume etc on the player bar.

**Comment by cwelsh1812** [comment]
Hi Sarah, if you see the post above you will see where to disable the pop ups, I have done this for the moment.

**Comment by dermotduffy** [comment]
@cwelsh1812  Mind answering this one:

* Are you using card_mod or any other integrations that may impact rendering?
* Does this happen on initial load, or do you do anything to trigger it?

**Comment by dermotduffy** [comment]
@cwelsh1812 One more: Can you try the HA live provider and see if it still happens?

**Comment by cwelsh1812** [comment]
@dermotduffy Yes I have card-mod installed though I have not made any changes to the frigate card.

It does not happen with the HA live provider.

**Comment by cwelsh1812** [comment]
@dermotduffy Ok, after deleting the cards and creating new ones, it's now not happening, although it does still happen on the preview of the card configuration page.

**Comment by dermotduffy** [comment]
@cwelsh1812 Thanks! Would it be possible to remove card_mod temporarily and see if it still happens? My guess is that it is related.

> It does not happen with the HA live provider.

So just `webrtc-card` then? Thanks, this narrows it down a lot.

**Comment by cwelsh1812** [comment]
> @cwelsh1812 Thanks! Would it be possible to remove card_mod temporarily and see if it still happens? My guess is that it is related.
> 
> > It does not happen with the HA live provider.
> 
> So just `webrtc-card` then? Thanks, this narrows it down a lot.

Sorry for the delay, I have removed card-mod and it still happens, although it is inconsistent, sometimes I can get it to happen on the live display in the dashboard, other times it only happens on the card preview.

**Comment by crankin91** [comment]
I'm experiencing the same issue, also webrtc-card. It happens immediately after reload. Let me know if I can provide any other details.

**Comment by dermotduffy** [comment]
Whilst working on #861 I found a bug that causes the `image` view to proclaim new media has been loaded repeatedly, which causes these toast messages to repeatedly show up. This is now fixed in code.

My theory is that this is responsible for the behavior we are seeing here, under the following conditions:

* The users `webrtc` installation is somehow broken such that it does not render.
* The user has `live.show_image_during_load` set to true (the default).

... in this case, since the webrtc element doesn't render, the card shows a static image waiting for it to load. That image refreshes every 1 seconds, and with the above bug (now fixed, but not in a build yet) that causes the toast message to repeatedly appear.

To confirm this theory, please try either:

 * Setting this value to false:

```yaml
live:
  show_image_during_load: false
```
... (if my theory is correct you'll just see a forever spinning 'Waiting for WebRTC card to load' message.

 * OR: Just create a 'native' [WebRTC Card](https://github.com/AlexxIT/WebRTC) (i.e. not a Frigate card) on your dashboard, and see if it works -- as this theory requires it to not work.

**Comment by cwelsh1812** [comment]
You are correct, forever spinning message !

**Comment by dermotduffy** [comment]
Thanks @cwelsh1812! So I think I'll mark this as fixed, since the underlying image component will now no longer exhibit this behavior from the next build (but you still have a separate webrtc problem that is not related to Frigate!).

Feel free to re-open if you / anyone thinks I've missed something here!

**Comment by keteflips** [comment]
I dont use webrtc and the spining message its my problem too.
