### ISSUE TITLE
Prevent users from playing video clips

### ISSUE THREAD

**Issue by miannelli516** [dermotduffy/frigate-hass-card#848]
Hello,
im trying to configure the new frigate card so that users can only see recent snapshots which is working however, when users click on the thumbnail, it starts playing the video clip as well. i want to be able to prevent users from playing video clips from the dashboard/lovelace.

**Comment by dermotduffy** [comment]
This is not currently supported.

Can you describe the usecase a little more? What do you want to work, and what to you want to be restricted? Why?

**Comment by miannelli516** [comment]
Sure. i have a live in nanny that has access to home assistant via an ipad on her wall and her mobile device. on her dashboard, i have picture cards configured so that she can see the last object that was detected for various cameras. im doing this via the built in home assistant picture card. i would love to give her access to see previous images/snapshots that the system detected in the event that she hears something or wants to check if their was movement/activity on a particular camera. right now the way i have it setup, she can only see the LAST object/activity that was detected. the reason why i do not want to give her access to video feeds is for privacy reasons and most importantly, when you play back the video it includes audio as well. if im outside having a private conversation, i dont want her to be able to play back the video. hope this makes sense?

**Comment by dermotduffy** [comment]
And presumably the user cannot edit the dashboard :-)

I don't think a card wide 'no_video' option makes sense since there will very rarely be wanted, but I do think we should be able to get what you want via other means. By changing the card menu buttons you can hide the live view, clips/clip view, the timeline view and just leave snapshots. At that stage, I think the only "broken" thing is that when you click on a snapshot it takes you to the matching clip.

If an option was added to prevent that click (getting from a snapshot to a video), would that cover the cases you're worried about? Have you seen any other "path" to get to clips?

I hasten to add: This is not any sort of real or even pretend 'security' (in the computer science sense), and there's zero guarantee some existing feature we don't think of, or new feature wouldn't be added to the card in future that adds back in access to clips via some other path. So if you cannot live with that possibility, this approach (and this card) may not be for you.

**Comment by miannelli516** [comment]
yes correct the user cannot edit the dashboard, or access frigate directly as i have it hidden from the side bar. Your solution to give an option that would prevent the clip from playing with they click on the snapshot/picture is exactly what im looking for! if that can be disabled somehow from a setting via the card, it would solve my exact issue.
