### ISSUE TITLE
Desktop so much faster than mobile. Why?

### ISSUE THREAD

**Issue by tyfoon** [dermotduffy/frigate-hass-card#886]
First of all; Thank you for this incredible work! What a card!

So my issues; When loading my camera page 6 cams + a snapshot gallery on chrome on my macbook, the page loads fully in about 2 seconds. When viewing the same page on my mobile (companion app on Android) the page takes minimal 5 seconds and in most cases up to 10.

Is there anything I can do to optimize?

HASS runs on a NUC <10% CPU. Frigate runs on another micro PC (J4125+GPU+Coral) at about 25% CPU. View provider in the card is the first option (homeassistan) but I have not done anything with webrtc yet. 

Sorry if I posted this in the wrong category

**Comment by dermotduffy** [comment]
Thanks for the feedback! Ultimately rendering 6 video streams is expensive, and mobile devices are usually just much weaker than a desktop PC, so this is not surprising. You are probably using the v4 release. Since that release I've put a fair bit of work into improving the card's performance (https://github.com/dermotduffy/frigate-hass-card/pull/861) -- it's just not in any build yet, so my suggestion is wait for the next release and play around with the `low` performance profile that will disable a whole bunch of features to make the card run/load faster. It also introduces a new `image` live provider that just shows refreshing snapshots of the camera (like picture glance card does), which should be much cheaper to render than actual video streams.

**Comment by tyfoon** [comment]
Thanks for quick reply.

I'm just watching some video's like [this](https://www.youtube.com/watch?v=SH9n3KhmTiM) on WEbRTC & your card but it is from about a year ago; would using this also improve performance?

**Comment by dermotduffy** [comment]
> I'm just watching some video's like [this](https://www.youtube.com/watch?v=SH9n3KhmTiM) on WEbRTC & your card but it is from about a year ago; would using this also improve performance?

Do you mean would using the WebRTC card provider improve performance? It won't improve the card's performance, but it could significantly reduce the latency between the camera and your feed (i.e. you move your hands in real-life, it'll show up much quicker on the video feed). Over the past year, HA itself has made lots of progress on WebRTC support, so there are other low latency options now, the [live providers table](https://github.com/dermotduffy/frigate-hass-card#available-live-providers) shows the options you have with links to them.

But this is really quite different from slow loading of the card itself. The live provider choice probably won't make much difference here, unless you used the new `image` provider since that is the only choice that does not load a live video stream.

**Comment by tyfoon** [comment]
Thanks again. Been testing a bit and by moving the card with the snapshot gallery to a dedicated tab I already got quite some improvement. Will wait for v4.

Other of topic  Q; Is it (already) possible to have a view (card) with cameras and the 'collapsed' timeline below that? So like the screenshot below but then with a timeline in the space where now the snapshots are and preferably a timeline that does not show all the cameras on top of each other, but is collapsed to a combined timeline so it does not take up that much space. Moving the line in the timeline would then show the clip of that cam that recorded the clip.

This would allow for a 'scrubber' like view similar to other NVR's

<img width="389" alt="Screen Shot 2022-10-31 at 08 50 55" src="https://user-images.githubusercontent.com/22179507/198959316-f037d82c-0621-4102-aea9-cc00c996b9d7.png">

**Comment by dermotduffy** [comment]
> This would allow for a 'scrubber' like view similar to other NVR's

If 'scrubber' means a small camera specific timeline that sits under the camera view and lets the user scan back and forth through the recording, then this too is already implemented and will be in the next build.

**Comment by tyfoon** [comment]
> > This would allow for a 'scrubber' like view similar to other NVR's
> 
> If 'scrubber' means a small camera specific timeline that sits under the camera view and lets the user scan back and forth through the recording, then this too is already implemented and will be in the next build.

yes & no.

Would not be camera specific; Would contain all events specified (or all events) of ALL cameras while you 'scrub'.

Take for instance a look at the screenshot below (just focus on the camera view & timeline). I don't know this specific NVR but they all have the same functionality. I have the same in Blue Iris for instance;  In the screenshot below the blue bar at the bottom (timeline of last x hours) with the red marking (events). While you 'scrub' the timeline (the white vertical line) the camera changes & plays to ANY camera that created that event the white bar is on.

If you only have 1 camera this is not super relevant (and you can actually do that already now with your card) but in most cases  there are multiple cams (in my case 6) and you want to see fast how for instance a person has moved over your property in the right order ideally with the recorded footage if available (not just the event) in between so you can create a real time view of what has happened (incl. seeing all the other things that where happening). 

![image](https://user-images.githubusercontent.com/22179507/199035700-67c8a4ab-8e99-48bf-80ad-da34b1da0a90.png)

**Comment by dermotduffy** [comment]
I think what is implemented is still probably pretty close. It would show the timeline for the camera in question, and also any camera configured as depending upon it (i.e. if you mark a camera as [depending](https://github.com/dermotduffy/frigate-hass-card#camera-dependency-configuration) on all other cameras, you'd effectively (I think!) get what you described.

**Comment by tyfoon** [comment]
Great. Looking forward to it.

**Comment by felipecrs** [comment]
Actually I think this conversation has deviated from the original issue which was about performance of the card in mobile.

But anyway I have a suggestion, I think a great recordings view would be some very similar to the Frigate's own recordings view.

**Comment by dermotduffy** [comment]
> But anyway I have a suggestion, I think a great recordings view would be some very similar to the Frigate's own recordings 
view.

Recordings were reworked as part of the recent media filter work (already in v4.1.0 branch), which allows showing recordings by time windows selections. That feels close enough to me, so I wasn't imagine additional work on this. If you have ideas there, lets chat on a separate issue. 

For now, I think I'll close this bug as it's effectively already implemented in the v4.1.0 branch.

**Comment by felipecrs** [comment]
By the way I played with some options in the card and I found this:


https://user-images.githubusercontent.com/29582865/222035689-0a13d0bb-c235-4887-85dc-0f66c8968ea4.mp4

It looks pretty great indeed!
