### ISSUE TITLE
Ability to 'cast' the birdseye camera

### ISSUE THREAD

**Issue by attzonko** [dermotduffy/frigate-hass-card#901]
**Is your feature request related to a problem? Please describe.**
No it is not.

**Describe the solution you'd like**
Currently I can cast the individual cameras. I am wondering if it is possible to enable casting for the 'birdseye' camera.

**Describe alternatives you've considered**
Can't think of any possible alternatives. 

**Additional context**
I want to be able to see all my camera feeds on a single TV screen, without finding a way to have the TV display HA in a browser.

**Comment by dermotduffy** [comment]
Right now this is not possible since the JSMPEG live view is not a "real" stream that a cast device can understand. Your options:

 * [Cast the entire card](https://github.com/dermotduffy/frigate-hass-card#casting-the-card).
 * Wait for this and Frigate v0.12: https://github.com/blakeblackshear/frigate-hass-integration/pull/386

**Comment by XxTopKillerzZ** [comment]
Any eta for merging into main?

**Comment by felipecrs** [comment]
It's now possible with Frigate 0.12. I would suggest closing this issue.

![image](https://user-images.githubusercontent.com/29582865/222014134-cbbe67de-0852-4f11-9745-5bc7bd6fb4c6.png)
