### ISSUE TITLE
Live title continually re-appears

### ISSUE THREAD

**Issue by Strikky** [dermotduffy/frigate-hass-card#905]
![afbeelding](https://user-images.githubusercontent.com/16107677/208672442-ac44c659-dc4b-433d-980f-5a3b6d0e1a96.png)

This text: “Live: Camera Voordeur” slide in from the bottom and after a moment it’s gone to come back again after (less then) a second. Not in regular interval and won’t stop.
I would be very happy when it totally gone or when it stay fixed.

Thanks
Jos

**Comment by dermotduffy** [comment]
You can disable it: https://github.com/dermotduffy/frigate-hass-card/issues/839#issuecomment-1258146228

Would you mind holding down your Frigate button and pasting the resulting diagnostics? I want to make sure the issue you have is the one I already fixed in the above issue (the fix just is not yet in a new build).

Thanks!

**Comment by dermotduffy** [comment]
This was already fixed in code (but not build): https://github.com/dermotduffy/frigate-hass-card/issues/839#issuecomment-1258146228
