### ISSUE TITLE
Issues with substream button

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#970]
Hi, let me know if you want more details but I think a video is worth more than words:

https://user-images.githubusercontent.com/29582865/221611538-f252048a-a474-4142-af5a-a4f25bd49a46.mp4

1. It should not show up as the first button with the default priority (50). I'd say it should follow the order of the buttons in the config list as all the other buttons.
2. When set to `opposing`, it shows up as vertical rather than on the other side.

For some reason I also have to apply the settings before I'm actually able to preview it sometimes (as it can be seen in the video), but this is a minor thing.

**Comment by felipecrs** [comment]
PS: this is using the codebase pre https://github.com/dermotduffy/frigate-hass-card/pull/966.

**Comment by dermotduffy** [comment]
> It should not show up as the first button with the default priority (50). I'd say it should follow the order of the buttons in the config list as all the other buttons.

This seems correct to me -- or perhaps I do not understand the issue.

* The icons _are_ ordered in the order of the visual editor list, but since you have cameras (the first button) on the `opposing` side, it means the submenu button (the second button) will be the first in line unless it's priority is higher.

> When set to opposing, it shows up as vertical rather than on the other side.

This is a bug, PR submitted.

**Comment by felipecrs** [comment]
> This seems correct to me -- or perhaps I do not understand the issue.

You are totally right. It's behaving correctly. My bad.

> This is a bug, PR submitted.

Awesome!
