### ISSUE TITLE
Select entities no longer display their labels

### ISSUE THREAD

**Issue by felipecrs** [dermotduffy/frigate-hass-card#972]
![chrome_r43K6BQuZo](https://user-images.githubusercontent.com/29582865/221746332-9b9460db-5c44-4132-b66a-22aa554c6a71.png)

![chrome_QfdwkkxxUC](https://user-images.githubusercontent.com/29582865/221746355-08a531a9-8272-42d5-b348-094d0d2f1685.png)

No apparent errors in the console logs.

**Comment by dermotduffy** [comment]
This is working for me when I choose a select entity without  the translations, so I'm guessing it's something to do with (and in your screenshot there **are** labels / numbers, just not the translated names). Sadly, I have no way to test that since I don't have a device that does this.

The code is:

```ts
      const title = stateObj.attributes.device_class
        ? this.hass.localize(
            `component.select.state.${stateObj.attributes.device_class}.${option}`,
          )
        : option;
```

Does the select entity you're using still specify a device_class in its state? If you can get access to the `hass` object (via devtools it would be the `_hass` property on the main `frigate-card` element), then try to run the above `localize` call and see if you still get translations?

As a reminder you managed to get this to work previously [here](https://github.com/dermotduffy/frigate-hass-card/issues/516#issuecomment-1103308955).

**Comment by felipecrs** [comment]
> As a reminder you managed to get this to work previously https://github.com/dermotduffy/frigate-hass-card/issues/516#issuecomment-1103308955.

Yes, it was working previously that's why I wrote _no longer display their labels_. :)

So, this is how it's supposed to work in my case:

```js
const entity = $0.hass.entities['select.camera_da_rua_night_vision']
console.log($0.hass.localize(`component.${entity.platform}.entity.select.${entity.translation_key}.state.1'))
"Desligado"
```

Some references:

- https://github.com/home-assistant/core/blob/dev/homeassistant/components/tuya/strings.json#L29-L35
- https://github.com/home-assistant/frontend/blob/dev/src/common/entity/compute_state_display.ts#L204-L218
  - According to the above there should be multiple ways to retrieve the translation indeed.

**Comment by dermotduffy** [comment]
Thanks for testing @felipecrs !
