### ISSUE TITLE
Birdseye tap to full screen individual cameras

### ISSUE THREAD

**Issue by jameseck** [dermotduffy/frigate-hass-card#998]
Currently I have 4 cameras that I'm feeding into an HA dashboard from Frigate.  This dashboard is displayed on a FireHD tablet and just shows the 4 cameras.  I have set the double tap action of each camera to show it full screen.

The problem I have is that the FireHD is not quite up to the task of displaying 4 cameras at once.

What I'd prefer to do is to show the birdseye view on the dashboard which would require less processing from the tablet.
I'd still like to be able to double tap on each camera to show an individual camera stream in full screen though.  As far as I know, this is not currently possible (tap action based on where you tap on the image).

**Comment by dermotduffy** [comment]
Hi @jameseck , thank you for the feedback!

I think you want it such that when you click on the part of the birdseye frame that represents each camera, for that to take you to a full view of _that_ camera.

If that's right, I don't think there's any way to do that. The position of the cameras in the birdseye frame may change based on what's happening, but that's completely invisible to the card -- it has no way of knowing if the top-left is camera A or B. Nor whether there's a quadrant of cameras, or a single camera. It can't know.

The new codebase (v4.1.0 -- not yet released) has some functionality that may help though:

 - Use a different live_provider. I bet the FireHD is up to the task of using the new `image` live_provider, this is simply a refreshing image of the camera -- and you can figure the refresh period.
 -  Use the new 'low' profile performance mode to try to make the card run better on lower end devices.
 - Use dependent cameras to list other cameras as depending upon the birdseye camera. This will give you a new menu that lets you choose between a configurable set of cameras (this isn't that big a deal, since you can already presumably use the camera selection menu to do similar).

Other ideas would be to render custom elements on the card that takes the user to each camera, and only has those icons show up when the camera is on the birdseye view. You don't need the new code base to do something like this.

**Comment by felipecrs** [comment]
Unless... Frigate could have an API like `get_camera_by_birdseye_pixel_location` that the card could use to fetch information of which camera to go to.

But I believe it's not worth the effort of implementing such thing.

**Comment by dermotduffy** [comment]
> Unless... Frigate could have an API like get_camera_by_birdseye_pixel_location that the card could use to fetch information of which camera to go to.

Yes! It's _technically_ implementable, just unlikely to be worth it given that it's probably a non-trivial amount of work across the card, the integration and the backend.

**Comment by dermotduffy** [comment]
Going to close this as I do not believe it is worth the work involved. I hope one of the workarounds will suffice. Feel free to continue the discussion if anyone has a better idea.
